### ISSUE TITLE
Screenshare not working in iOS (shows red screen)

### ISSUE THREAD

**Issue by irohitb** [react-native-webrtc/react-native-webrtc#1106] opened 2021-12-22 11:36 UTC
#### Expected behavior
- Screenshare should work in iOS but instead I am getting a red screen
#### Observerd behavior
- Getting red screen when starting screenshare
PS: Running it on a real device

#### Steps to reproduce the problem
- Clone this repo: https://github.com/irohitb/screenshare-webrtc
- cd ios && pod install
- create/update app group 
- plugin your phone and run on physical device connected via usb.

#### Platform information

* **React Native version**:0.66.3
* **Plugin version**: 1.92.2 & 1.94.0
* **OS**: ios
* **OS version**: 15

**Comment by AliSaeed090** [comment] 2022-01-09 14:52
@irohitb 
How did you solve this issue? Please help. I am facing same issue

**Comment by irohitb** [comment] 2022-01-09 19:04
@AliSaeed090 Haven't resolved it yet.

**Comment by AliSaeed090** [comment] 2022-01-09 19:47
I am also trying on IOS to but it shows red screen. My logs when app loaded first time.
[connection] nw_socket_handle_socket_event [C5:1] Socket SO_ERROR [61: Connection refused] 2022-01-10 00:40:13.630319+0500 wepoc[33369:8892041] [connection] nw_connection_get_connected_socket [C5] Client called nw_connection_get_connected_socket on unconnected nw_connection 2022-01-10 00:40:13.630398+0500 wepoc[33369:8892041] TCP Conn 0x280119550 Failed : error 0:61 [61]

**Comment by irohitb** [comment] 2022-01-11 03:41
I will work on this again over weekend but did you do any changes in the sample repo I shared @AliSaeed090 ? like to get screen share on host?

**Comment by AliSaeed090** [comment] 2022-01-11 16:04
@irohitb  I initially followed yours but it was not working so then I followed jitsi meet docs, it works only remote side, But I am using your JS side code. I am still getting red screen on Host side

**Comment by irohitb** [comment] 2022-01-11 16:09
@AliSaeed090 on the native side (iOS), what is the difference between my code and Jitsi code? Like I followed their instruction. 

Did I do something differently?

**Comment by AliSaeed090** [comment] 2022-01-11 16:25
@irohitb I saw your code again its same as I did. You need to test by sending screen share stream to remote peer. And see if you can see screen on other hand. As I think we must be doing something wrong or something is buggy on latest version. or may be something on JS side. Can you please let me know how did you know about JS side code ? I can't see any docs on JS side code

**Comment by Aaronphy** [comment] 2022-09-22 03:38
> @irohitb I saw your code again its same as I did. You need to test by sending screen share stream to remote peer. And see if you can see screen on other hand. As I think we must be doing something wrong or something is buggy on latest version. or may be something on JS side. Can you please let me know how did you know about JS side code ? I can't see any docs on JS side code

Could you share a sample code about sending screen share to remote peer?

**Comment by saghul** [comment] 2022-09-22 06:59
Closing since this was never reproducible. FTR, looking at one's own screen-share track locally is not possible, only the remote party can.

**Closed by saghul** 2022-09-22 06:59 UTC

**Comment by Aaronphy** [comment] 2022-09-23 02:34
> 

How to send the stream to remote?  Could you give me a sample?

**Comment by saghul** [comment] 2022-09-23 05:12
It's a stream, same way you send normal audio / video streams.
