### ISSUE TITLE
[bug] DataChannel base64 convert 

### ISSUE THREAD

**Issue by yan-jie** [react-native-webrtc/react-native-webrtc#1419] opened 2023-07-12 08:42 UTC
#### Expected Behavior:
DataChannel receive buffer data can be return correct

#### Observed Behavior:
now it return empty array

#### Steps to reproduce the issue:
see code below: 
https://github.com/react-native-webrtc/react-native-webrtc/blob/master/src/RTCDataChannel.ts#L157

in base64-js library, toByteArray is a pure function that only return a buffer array.

**Comment by saghul** [comment] 2023-07-12 08:52
Not sure I understand. What do you get and what do you expect?

**Comment by yan-jie** [comment] 2023-07-13 01:19
I mean, the call to base64-js is not correct. should be

``` javascript
data = base64.toByteArray(ev.data);
```

**Comment by 8BallBomBom** [comment] 2023-07-13 04:32
Any chance you can provide a code sample?
Having issues reproducing.

```
Sender [starting string] -> Hello World... :o!
Sender [converted to arraybuffer] -> [72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100, 46, 46, 46, 32, 58, 111, 33]
Sender [back to string] -> Hello World... :o!
Sender -> Forwarding ArrayBuffer

Receiver - Got Data
Receiver [arraybuffer] -> [72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100, 46, 46, 46, 32, 58, 111, 33]
Receiver [converted to string] -> Hello World... :o!
```

**Comment by saghul** [comment] 2023-07-13 05:07
The call to toByteArray returns UInt8Array (not just Array, since RN supports the former). According to the spec we need to provide an ArrayBuffer in the event: https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/data so we access the array buffer.

**Comment by yan-jie** [comment] 2023-07-13 07:46
Thanks for your reminder, I realized where the problem is. The react native environment I am working in does not have uint8Array, so the toByteArray method of base64-js returns a standard Array and there is no buffer property. I need to introduce shim to support Uint8Array

**Comment by saghul** [comment] 2023-07-13 07:49
Unless you are using a really really old version (which we likely don't support) it should be there.

I'm going to close this since it's not an issue with the plugin.

**Closed by saghul** 2023-07-13 07:49 UTC
Labels: bug, needs-confirmation
