### ISSUE TITLE
[iOS] dataChannelDidChangeState crash

### ISSUE THREAD

**Issue by Minishlink** [react-native-webrtc/react-native-webrtc#962] opened 2021-04-01 11:41 UTC
Hello, after this PR https://github.com/react-native-webrtc/react-native-webrtc/pull/919 (issue https://github.com/react-native-webrtc/react-native-webrtc/issues/917) I have a crash when a connection is made. Specifically the crash occurs in `dataChannelDidChangeState` in `RTCDataChannel.m` : a `NSDictionnary` is created with the channel id but `channel.originDataChannelId` can be `null`.
Note that it doesn't always happen so it looks like a race condition.

#### Expected behavior

Connecting to a peer should not make the app crash randomly on iOS.

#### Platform information

* **React Native version**: 0.63.4
* **Plugin version**: 1.89.1
* **OS**: iOS
* **OS version**: 14

**Comment by saghul** [comment] 2021-04-01 13:41
Any chance you can provide a fix? I think we'd need a sample app which creates a couple of peer connections and negotiates some datachannels between them. Ping @xilin

**Comment by xilin** [comment] 2021-04-02 16:47
A sample app will be helpful. Could you give an example how did you create peer connections and datachannels @Minishlink ? And do you have the crash stack trace? If `dataChannelDidChangeState` is called, that means `dataChannel.delegate = self;` was called, so `originDataChannelId` should have already be set.

**Comment by hoaphantn7604** [comment] 2021-04-15 03:37
My temporary solution.

<img width="707" alt="Screen Shot 2021-04-15 at 10 32 37" src="https://user-images.githubusercontent.com/50919571/114810468-5801b080-9dd6-11eb-9b6d-1ade19682dca.png">

**Comment by ibc** [comment] 2021-04-21 10:22
> I think we'd need a sample app which creates a couple of peer connections and negotiates some datachannels between them.

Not sure if related, but here a code that does exactly that and produces a crash:

https://github.com/react-native-webrtc/react-native-webrtc/issues/971

**Comment by ibc** [comment] 2021-04-21 11:59
The following sample code (it communicates two local PeerConnections by creating a DataChannel) crashes on iOS, it can be reproduced in simulator of iOS 14.4):

```ts
const pc1 = new RTCPeerConnection();
const pc2 = new RTCPeerConnection();

pc1.createDataChannel('foo', { ordered: true });

pc1.addEventListener('icecandidate', event => {
  const candidate = event.candidate;

  if (candidate) {
    pc2.addIceCandidate(candidate);
  }
});

pc2.addEventListener('icecandidate', event => {
  const candidate = event.candidate;

  if (candidate) {
    pc1.addIceCandidate(candidate);
  }
});

const offer = await pc1.createOffer();

await pc1.setLocalDescription(offer);
await pc2.setRemoteDescription(offer);

const answer = await pc2.createAnswer();

await pc2.setLocalDescription(answer);
await pc1.setRemoteDescription(answer); // <-- Crash happens here!
```

Crash:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2049d77f _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff204a8ec4 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.5 + 0
	4   CoreFoundation                      0x00007fff2048bcb7 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 235
	5   CoreFoundation                      0x00007fff2041f773 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 49
	6   mobileapp-stage                     0x000000010b33155a -[WebRTCModule(RTCDataChannel) dataChannelDidChangeState:] + 282
	7   WebRTC                              0x000000010da3cbef _ZN6webrtc26DataChannelDelegateAdapter13OnStateChangeEv + 89
	8   WebRTC                              0x000000010de8976a _ZN6webrtc15SctpDataChannel8SetStateENS_20DataChannelInterface9DataStateE + 40
	9   WebRTC                              0x000000010de898b4 _ZN6webrtc15SctpDataChannel11UpdateStateEv + 282
	10  WebRTC                              0x000000010de8b289 _ZN6webrtc23webrtc_new_closure_impl11ClosureTaskIZNS_15SctpDataChannel4InitEvE3$_1E3RunEv + 25
	11  WebRTC                              0x000000010da7e285 _ZN3rtc6Thread17QueuedTaskHandler9OnMessageEPNS_7MessageE + 39
	12  WebRTC                              0x000000010da7da4b _ZN3rtc6Thread8DispatchEPNS_7MessageE + 143
	13  WebRTC                              0x000000010da7c952 _ZN3rtc6Thread15ProcessMessagesEi + 140
	14  WebRTC                              0x000000010da7de92 _ZN3rtc6Thread6PreRunEPv + 76
	15  libsystem_pthread.dylib             0x00007fff60c8e109 _pthread_start + 148
	16  libsystem_pthread.dylib             0x00007fff60c89b8b thread_start + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
terminating with uncaught exception of type NSException
```

**Comment by xilin** [comment] 2021-04-26 04:24
@ibc thanks for the sample code.

![first](https://user-images.githubusercontent.com/543395/116028581-05ec4500-a68a-11eb-98d9-496faf1fbc01.png)
![second](https://user-images.githubusercontent.com/543395/116028624-1e5c5f80-a68a-11eb-8afd-440673f040cf.png)

Looks like even when we only create one dataChannel object, the delegate return two different instances... Need a deeper look of how this happened.

**Comment by ibc** [comment] 2021-04-26 08:03
> Looks like even when we only create one dataChannel object, the delegate return two different instances... Need a deeper look of how this happened.

In my sample code above we are creating a DataChannel in pc1 plus another DataChannel that is automatically created in pc2 after SDP negotiation => `pc2.ondatachannel` event.

I've added it to the sample code to make it clear:

```ts
const pc1 = new RTCPeerConnection();
const pc2 = new RTCPeerConnection();

pc1.createDataChannel('foo', { ordered: true });

pc1.addEventListener('icecandidate', event => {
  const candidate = event.candidate;

  if (candidate) {
    pc2.addIceCandidate(candidate);
  }
});

pc2.addEventListener('icecandidate', event => {
  const candidate = event.candidate;

  if (candidate) {
    pc1.addIceCandidate(candidate);
  }
});

pc2.addEventListener('datachannel', event => {
	const datachannel = event.channel;

	console.log('datachannel created in pc2:', datachannel);
});

const offer = await pc1.createOffer();

await pc1.setLocalDescription(offer);
await pc2.setRemoteDescription(offer);

const answer = await pc2.createAnswer();

await pc2.setLocalDescription(answer);
await pc1.setRemoteDescription(answer); // <-- Crash happens here!
```

**Comment by saghul** [comment] 2021-05-04 13:06
Quick heads up. I spent some time today working on a fix. I don't have a full fix yet, but I do know something: relying on the actual data channel ID is a no-go.

```
var pc = new RTCPeerConnection();
var dc = pc.createDataChannel("my channel");

console.log("Channel id: " + dc.id);
```

This returns `null` on both Firefox and Chrome, for instance.

In order to fix it, I'm creating wrapper objects around the native data channel objects, with a UUID we generate in JS to keep track of them. This way, the mechanism to keep track of them is independent of the actual channel ID.

**Comment by ibc** [comment] 2021-05-04 13:27
But this is expected as I commented in https://github.com/react-native-webrtc/react-native-webrtc/pull/972 and you said that it doesn't matter because the lib always sets one.

**Comment by saghul** [comment] 2021-05-04 13:30
I was wrong, it's not set early enough. It starts at -1 and gets set once negotiated. So in the meantime you have a DC with id -1. And if you create 2 of them... well you have a problem.

**Comment by xilin** [comment] 2021-05-09 16:52
Sorry for the late reply, and my broken fix on the [PR](https://github.com/react-native-webrtc/react-native-webrtc/pull/919).

@ibc Thanks for your example. I believe the root cause is that:

![sc1](https://user-images.githubusercontent.com/543395/117580007-5488ed00-b128-11eb-8b30-4d39a19a3f32.png)
![sc2](https://user-images.githubusercontent.com/543395/117580010-56eb4700-b128-11eb-8ffc-42ce4da9f025.png)

The crash happened because inside webrtc's code, it generated a new data channel object, which wasn't created under our control. See codes in the links:

https://github.com/jitsi/webrtc/blob/master/pc/data_channel_controller.cc#L259
https://github.com/jitsi/webrtc/blob/master/pc/data_channel_controller.cc#L327
https://github.com/jitsi/webrtc/blob/master/sdk/objc/api/peerconnection/RTCPeerConnection.mm#L161
https://github.com/react-native-webrtc/react-native-webrtc/blob/master/ios/RCTWebRTC/WebRTCModule%2BRTCPeerConnection.m#L543

@saghul your have already foreseen the problem when review my PR https://github.com/react-native-webrtc/react-native-webrtc/pull/919#discussion_r548158564 👍 

I agree that `relying on the actual data channel ID is a no-go`. My [PR](https://github.com/react-native-webrtc/react-native-webrtc/pull/919) is too fragile. Wait for your better solution @saghul .

**Comment by saghul** [comment] 2021-05-10 06:45
I have a started the refactor for fixing this, hopefully I can have a PR tomorrow.

**Comment by saghul** [comment] 2021-05-18 15:39
WIP PR in #1002. Actual fix in https://github.com/react-native-webrtc/react-native-webrtc/pull/1002/commits/6f57d59a69e516c5eca5bb455416a16ce36b8eca

I'm still debating the approach. We could do the creation async and report creation errors on `onerror` but that's not how browsers behave.

**Comment by saghul** [comment] 2021-05-19 08:24
The PR is now ready and the test @ibc posted works just fine. I also fixed some more corner cases when closing datachannels.

**Closed** 2021-05-19 09:57 UTC

**Comment by Minishlink** [comment] 2021-05-21 06:24
Thanks @saghul! Unfortunately the fix introduced another issue.

It throws `[RTCDataChannel peerConnectionId]: unrecognized selector sent to instance 0x60000383c5a0` when `channel.peerConnectionId` is accessed in `didReceiveMessageWithBuffer`.
If you don't send any message through the data channel all is well.

**Comment by ibc** [comment] 2021-05-21 07:12
@Minishlink can you please report a separate issue for that, please? and include STR?
