### ISSUE TITLE
After react-native-webrtc update mediaDevices.enumerateDevices() not working

### ISSUE THREAD

**Issue by krishnapsarthi** [react-native-webrtc/react-native-webrtc#662] opened 2019-07-17 11:36 UTC
@saghul ,

I have updated react-native-webrtc version to latest "1.69.2".

**Expected behavior:**
Api `mediaDevices.enumerateDevices()` should be resolved with sourceInfos.

**Observed behavior**
With updates we have to use 
`mediaDevices.enumerateDevices().then(sourceInfos => { ` instead of
`MediaStreamTrack.getSources(sourceInfos => {`

mediaDevices.enumerateDevices() promise is not getting resolved with result.

Previously it was working for me with `MediaStreamTrack`.

Please let me know if it needs anything other than this.

**Platform information**
**"react"**: "16.6.0",
 **"react-dom"**: "^16.3.2",
**"react-native"**: "0.57.4",
 **"react-native-webrtc"**: "1.69.2"

Thanks

**Comment by saghul** [comment] 2019-07-17 14:39
Can you paste a code snipped showing how you are using it?

**Comment by krishnapsarthi** [comment] 2019-07-17 15:02
`mediaDevices.enumerateDevices().then(sourceInfos => {
            let videoSourceId;
            for (let i = 0; i < sourceInfos.length; i++) {
                const sourceInfo = sourceInfos[i];
                if (sourceInfo.kind === 'video' && sourceInfo.facing === (isFront ? 'front' : 'back')) {
                    videoSourceId = sourceInfo.id;
                    console.log("videoSourceId", videoSourceId);
                }
            }
            mediaDevices.getUserMedia({
                audio: true,
                video: {
                    mandatory: {
                        minWidth: 500, // Provide your own width, height and frame rate here
                        minHeight: 300,
                        minFrameRate: 30
                    },
                    facingMode: (isFront ? "user" : "environment"),
                    optional: (videoSourceId ? [{ sourceId: videoSourceId }] : [])
                }
            }, (stream) => {
                if (stream) {
                    stream.getAudioTracks()[0].enabled = isMicEnabled;
                }
                let remoteUser = {
                    name: userName,
                    stream: stream,
                    streamURL: stream.toURL(),
                    isScreenShare: false,
                    webCamNotFound: stream ? true : false,
                    isIos: true,
                };
                if (!isWebinarOn) {
                    this.setState({ localStream: stream, localVideo: remoteUser });
                    setTimeout(() => {
                        for (let peer in this.pc1LocalList) {
                            this.createPeerConnection(peer);
                        }
                    }, 50);
                }
            }, error => {
                console.log("Error occured", error.message);
                throw error;
            });
        });`

**Comment by krishnapsarthi** [comment] 2019-07-17 15:22
@saghul 

Does this PR changes has been merged in to master yet?

Here i got your reply
https://github.com/react-native-webrtc/react-native-webrtc/issues/640

Thanks

**Comment by saghul** [comment] 2019-07-17 15:29
Yes, it's merged and available in 1.69.2. Your code is checking if the `kind` is `video`, but that's not a valid kind, it has to be either `videoinput` or `audioinput`. Please log the `sourceInfos` object you get in the promise. It does resolve, I see no code path that yields to it not being resolved.

**Comment by krishnapsarthi** [comment] 2019-07-17 15:31
> Yes, it's merged and available in 1.69.2. Your code is checking if the `kind` is `video`, but that's not a valid kind, it has to be either `videoinput` or `audioinput`. Please log the `sourceInfos` object you get in the promise. It does resolve, I see no code path that yields to it not being resolved.

Update the code to `videoinput ` but still getting same result.
At my end it never comes inside then

**Comment by saghul** [comment] 2019-07-17 15:48
I don't know what to suggest, to be honest, is the component mounted? Are you running any other WebRTC related API calls? Can you create a small repo which reproduces the problem?

**Comment by krishnapsarthi** [comment] 2019-07-17 15:55
> I don't know what to suggest, to be honest, is the component mounted? Are you running any other WebRTC related API calls? Can you create a small repo which reproduces the problem?

With previous code `MediaStreamTrack.getSources(sourceInfos => { ` it was working for me.
Does it some thing related to react-native version?

**Comment by saghul** [comment] 2019-07-17 17:16
> Does it some thing related to react-native version?

No, it shouldn't matter.

**Comment by krishnapsarthi** [comment] 2019-07-18 12:43
@saghul ,

I have tried to call function before every api call and that worked for me.
Still doesn't able to figured out the root cause of that.

**Comment by saghul** [comment] 2019-07-18 14:18
Not sure I follow. Does `mediaDevices.enumerateDevices` work now? What did you change? Is `mediaDevices.getUserMedia` the problem now? I see you are calling it with callbacks, but that won't work, it returns a promise. This was mentioned in the release notes for 1.69.0 as a major change: https://github.com/react-native-webrtc/react-native-webrtc/releases/tag/1.69.0

**Comment by krishnapsarthi** [comment] 2019-07-18 15:02
@saghul ,

I have update callbacks to promise, but still doesn't worked for me.
The `mediaDevices.enumerateDevices ` i have tried this at the parent component then that worked, but not sure what is the problem to work at the same place. 
This `mediaDevices.getUserMedia ` also not worked for me.
Not sure what issue is causing that but if i try to use the way i was using `MediaStreamTrack.getSources ` then it doesn't work.

**Comment by saghul** [comment] 2019-07-18 17:18
> I have updated callbacks to promise, but still doesn't worked for me.

Show me the code.

**Comment by krishnapsarthi** [comment] 2019-07-19 12:51
@saghul,

```
mediaDevices.enumerateDevices().then(sourceInfos => {
  let videoSourceId;
  for (let i = 0; i < sourceInfos.length; i++) {
    const sourceInfo = sourceInfos[i];
    if(sourceInfo.kind == "videoinput" && sourceInfo.facing == (isFront ? "front" : "back")) {
      videoSourceId = sourceInfo.deviceId;
    }
  }
  mediaDevices.getUserMedia({
    audio: true,
    video: {
      mandatory: {
        minWidth: 500, 
        minHeight: 300,
        minFrameRate: 30
      },
      facingMode: (isFront ? "user" : "environment"),
      optional: (videoSourceId ? [{sourceId: videoSourceId}] : [])
    }
  })
  .then(stream => {
    this.setState({
     stream
    })
  })
  .catch(error => {
    // Log error
  });
});
```

If try this before every api call and store the stream in state and pass that to child component then i get the stream and streamURL but that doesn't work with RTCView.

**Comment by saghul** [comment] 2019-07-19 13:21
So, this is now the 3rd different thing you are reporting on this very issue. First `enumerateDevices` didn't work, then it was `getUserMedia`, and now it's the rendering?!

You provide no logs,  just an incomplete snippet of code, it's virtually impossible for me to figure out what could be wrong, sorry.

**Comment by krishnapsarthi** [comment] 2019-07-19 13:28
> So, this is now the 3rd different thing you are reporting on this very issue. First `enumerateDevices` didn't work, then it was `getUserMedia`, and now it's the rendering?!
> 
> You provide no logs, just an incomplete snippet of code, it's virtually impossible for me to figure out what could be wrong, sorry.

@saghul 
Sorry, But have tried with just replacing the api call, It didn't worked for me. 
Then I have tried with call api at parent level and then send that stream to child component and use it, now have streamURL and stream but that not working.

**Comment by krishnapsarthi** [comment] 2019-07-22 08:07
@saghul ,

I am getting error on xcode as 'Thread 1: signal SIGABRT'

**Comment by krishnapsarthi** [comment] 2019-07-22 13:04
@saghul ,

The reason behind the react-native-webrtc update is, we need to integrate jssip into oiur webrtc as per suggestions in [https://github.com/versatica/JsSIP/issues/526](url), After react-native-webrtc we are going to try integration of jssip lib.
Let me know do we require to update react-native-webrtc for that?

**Comment by 8BallBomBom** [comment] 2019-07-23 17:11
I'm not able to reproduce any of the issue you are experiencing using the latest master branch version which is M75 along with RN 59.8 have you tried upgrading your RN version to 59.8 and also made sure to do a clean when building?

**Comment by saghul** [comment] 2019-08-04 08:24
No follow up, closing.

**Closed by saghul** 2019-08-04 08:24 UTC
