### ISSUE TITLE
Calling VideoTrack.enabled freezes the video

### ISSUE THREAD

**Issue by CSantosM** [react-native-webrtc/react-native-webrtc#659] opened 2019-07-08 09:26 UTC
User A joins a room, the  video is working.
I want to disable / enable the video so i call to `VideoTrack.enabled = !enable`. 

I noticed thet the problem is the same when two users are connected. User 2 see the User 1 video frozen.
Video shows frozen with the last frame for **8/10** tests. Black screen appear for 2/10 test.

#### Expected behavior
User A see a black screen on the RTCView.

#### Observerd behavior
User A see a video freeze with the last frame.

#### Steps to reproduce the problem
User A join a room, the video is working
User A disables their video

#### Platform information

* **React Native version**: 0.59.9
* **Plugin version**: 1.69.2
* **OS**:  Android
* **OS version**: 5.1 / 7.1

**Comment by saghul** [comment] 2019-07-08 10:16
This is a duplicate of https://github.com/react-native-webrtc/react-native-webrtc/issues/643  When we disable a track currently nothing is being sent, hence the last frame being frozen.

Please follow-up on the aforementioned issue.

**Closed by saghul** 2019-07-08 10:16 UTC
