### ISSUE TITLE
App Crashed when clicked cancel button of start screen capture popups

### ISSUE THREAD

**Issue by Aaronphy** [react-native-webrtc/react-native-webrtc#1230] opened 2022-11-15 11:46 UTC
#### Expected Behavior

should not be crashed

#### Observed Behavior

![image](https://user-images.githubusercontent.com/16236806/201911734-37862757-891e-4cff-8dcc-a0a131cc0bf1.png)

#### Steps to reproduce the issue
 the screen share example 

#### Platform Information

* **React Native Version**:  0.70.5
* **Plugin Version**: 1.100.1
* **OS**:  Android 
* **OS Version**: 11

**Comment by saghul** [comment] 2022-11-15 14:30
Can you please get the `adb logcat` ?

**Comment by Aaronphy** [comment] 2022-11-16 04:30
> Can you please get the `adb logcat` ?

yes
```shell
11-16 12:28:40.075   296  5164 I chatty  : uid=1041(audioserver) HwBinder:296_3 identical 586 lines
11-16 12:28:40.163   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:40.163   389   475 D AudioFlinger: mixer(0xf6159030) throttle end: throttle time(8)
11-16 12:28:40.168   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:40.683   296  5164 I chatty  : uid=1041(audioserver) HwBinder:296_3 identical 10 lines
11-16 12:28:40.770   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:40.799  4246  4309 I ReactNativeJS: retry 1 times, error: please check the open
11-16 12:28:40.837   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:40.941   525  2174 I ActivityTaskManager: START u0 {cmp=com.android.systemui/.media.MediaProjectionPermissionActivity} from uid 10122
11-16 12:28:40.857   296  5164 I chatty  : uid=1041(audioserver) HwBinder:296_3 identical 1 line
11-16 12:28:40.920   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:40.941   525   546 D EventSequenceValidator: Transition from ACTIVITY_FINISHED to INTENT_STARTED
11-16 12:28:40.954   424   424 I perfetto: ing_service_impl.cc:758 Configured tracing session 246, #sources:1, duration:5000 ms, #buffers:1, total buffer size:4096 KB, total sessions:1, uid:1071 session name: ""
11-16 12:28:40.956   413   413 I perfetto: probes_producer.cc:230  Ftrace setup (target_buf=246)
11-16 12:28:40.961   525   546 D EventSequenceValidator: Transition from INTENT_STARTED to ACTIVITY_LAUNCHED
11-16 12:28:40.973   525  2174 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (427004015)
11-16 12:28:40.973   525  2174 W InputReader: Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.973   525  2174 W InputReader: Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.973   525  2174 W InputReader: Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.973   525  2174 W InputReader: Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.973   525  2174 W InputReader: Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.973   525  2174 W InputReader: Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.973   525  2174 W InputReader: Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.973   525  2174 W InputReader: Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.973   525  2174 W InputReader: Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.973   525  2174 W InputReader: Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.974   525  2174 W InputReader: Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.974   525  2174 W InputReader: Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.974   525  2174 W InputReader: Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.974   525  2174 W InputReader: Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.974   525  2174 W InputReader: Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.974   525  2174 W InputReader: Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.974   525  2174 W InputReader: Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.974   525  2174 W InputReader: Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.974   525  2174 W InputReader: Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.974   525  2174 W InputReader: Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:40.983   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:41.062   525   525 W NotificationHistory: Attempted to add notif for locked/gone/disabled user 0
11-16 12:28:41.019   296  5164 I chatty  : uid=1041(audioserver) HwBinder:296_3 identical 1 line
11-16 12:28:41.038   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:41.065   413   413 I perfetto: ftrace_procfs.cc:176    enabled ftrace
11-16 12:28:09.391     0     0 W perfetto: enabled ftrace
11-16 12:28:41.098   310   365 D goldfish-address-space: claimShared: Ask to claim region [0x3ef56b000 0x3ef9c8000]
11-16 12:28:41.110   310   365 D goldfish-address-space: claimShared: Ask to claim region [0x3ef9c8000 0x3efe25000]
11-16 12:28:41.115   310   365 D goldfish-address-space: claimShared: Ask to claim region [0x3ee39c000 0x3ee7f9000]
11-16 12:28:41.165   310   365 D goldfish-address-space: claimShared: Ask to claim region [0x3efe53000 0x3efe54000]
11-16 12:28:41.168   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:41.172   310   365 D goldfish-address-space: claimShared: Ask to claim region [0x3efe54000 0x3efe55000]
11-16 12:28:41.173   310   365 D goldfish-address-space: claimShared: Ask to claim region [0x3efe55000 0x3efe56000]
11-16 12:28:41.192   525   551 D ArtManagerInternalImpl: /data/misc/iorapd/com.android.systemui/30/com.android.systemui.media.MediaProjectionPermissionActivity/compiled_traces/compiled_trace.pb doesn't exist
11-16 12:28:41.195   525   551 I ActivityTaskManager: Displayed com.android.systemui/.media.MediaProjectionPermissionActivity: +237ms
11-16 12:28:41.210   525   546 D EventSequenceValidator: Transition from ACTIVITY_LAUNCHED to ACTIVITY_FINISHED
11-16 12:28:41.217   691   691 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|com.mbes|651859831|null|10122
11-16 12:28:41.218   691   691 D InterruptionStateProvider: No heads up: unimportant notification: 0|com.mbes|651859831|null|10122
11-16 12:28:41.233   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:41.239   525   546 D CompatibilityChangeReporter: Compat change id reported: 136219221; UID 10122; state: ENABLED
11-16 12:28:42.901   296  5164 I chatty  : uid=1041(audioserver) HwBinder:296_3 identical 33 lines
11-16 12:28:42.998   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:43.015   691  1146 D OpenGLRenderer: endAllActiveAnimators on 0xb99ef950 (RippleDrawable) with handle 0xb7f34130
11-16 12:28:43.016   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:43.034   310   365 D goldfish-address-space: claimShared: Ask to claim region [0x3ec8e7000 0x3ed1ce000]
11-16 12:28:43.042   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:43.068   525 29784 W InputReader: Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.068   525 29784 W InputReader: Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.068   525 29784 W InputReader: Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.068   525 29784 W InputReader: Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.068   525 29784 W InputReader: Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.068   525 29784 W InputReader: Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.068   525 29784 W InputReader: Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.068   525 29784 W InputReader: Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.068   525 29784 W InputReader: Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.068   525 29784 W InputReader: Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.068   525 29784 W InputReader: Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.068   525 29784 W InputReader: Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.068   525 29784 W InputReader: Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.069   525 29784 W InputReader: Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.069   525 29784 W InputReader: Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.069   525 29784 W InputReader: Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.069   525 29784 W InputReader: Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.069   525 29784 W InputReader: Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.069   525 29784 W InputReader: Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.069   525 29784 W InputReader: Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
11-16 12:28:43.072   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:43.075  4246  4309 I ReactNativeJS: '[get-stream]:error', { name: 'Error',
11-16 12:28:43.075  4246  4309 I ReactNativeJS:   message: 'NotAllowedError',
11-16 12:28:43.075  4246  4309 I ReactNativeJS:   constraintName: undefined }
11-16 12:28:43.084   445   574 D AudioAnalytics: gc(1700, 2000): log size:1700 item map size:5, item map items:1700
11-16 12:28:43.102   525  5180 D HostConnection: HostConnection::get() New Host Connection established 0xb1791c70, tid 5180
11-16 12:28:43.105   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: Exception in native call
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:102)
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:73)
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:69)
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:356)
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: 	at com.facebook.jni.NativeRunnable.run(Native Method)
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:938)
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:223)
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
11-16 12:28:43.111  4246  4310 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:923)
11-16 12:28:43.127   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:43.148   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:43.169   525  5180 D HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0
11-16 12:28:43.171   525  5180 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
11-16 12:28:43.171   525  5180 D EGL_emulation: eglCreateContext: 0xedb78010: maj 3 min 0 rcv 3
11-16 12:28:43.172   525  5180 D EGL_emulation: eglMakeCurrent: 0xedb78010: ver 3 0 (tinfo 0xb8b880f0) (first time)
11-16 12:28:43.199   691   707 I ndroid.systemu: NativeAlloc concurrent copying GC freed 11576(743KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 7935KB/15MB, paused 846us total 110.945ms
11-16 12:28:43.310   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:43.339   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:43.568   310   365 D goldfish-address-space: claimShared: Ask to claim region [0x3ee39c000 0x3eec83000]
11-16 12:28:43.582   310   365 D goldfish-address-space: claimShared: Ask to claim region [0x3ef56b000 0x3efe52000]
11-16 12:28:43.586   310   365 D goldfish-address-space: claimShared: Ask to claim region [0x3f2c86000 0x3f356d000]
11-16 12:28:43.833  4246  4290 I OpenGLRenderer: Davey! duration=705ms; Flags=1, IntendedVsync=431927299966738, Vsync=431927399966734, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=431927413845663, AnimationStart=431927413883663, PerformTraversalsStart=431927414546663, DrawStart=431927977532663, SyncQueued=431927981563663, SyncStart=431927982875663, IssueDrawCommandsStart=431927982938663, SwapBuffers=431928001092663, FrameCompleted=431928006786663, DequeueBufferDuration=244000, QueueBufferDuration=1674000, GpuCompleted=1262720385317,
11-16 12:28:43.841  4246  4246 I Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
11-16 12:28:43.842  4246  4246 W unknown:ReactContextBaseJavaModule: Catalyst Instance has already disappeared: requested by Timing
11-16 12:28:43.846  4246  4310 W unknown:ReactContextBaseJavaModule: Catalyst Instance has already disappeared: requested by DeviceInfo
11-16 12:28:43.846  4246  4310 W unknown:ReactContextBaseJavaModule: Catalyst Instance has already disappeared: requested by AppState
11-16 12:28:43.846  4246  4310 W unknown:ReactContextBaseJavaModule: Catalyst Instance has already disappeared: requested by NativeAnimatedModule
11-16 12:28:43.846  4246  4310 W unknown:ReactContextBaseJavaModule: Catalyst Instance has already disappeared: requested by FrescoModule
11-16 12:28:43.851   525   626 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=314, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10122 AdministratorUids: [] RequestorUid: 10122 RequestorPackageName: com.mbes] ] (release request)
11-16 12:28:43.869  4246  4246 E unknown:ReactInstanceManager: destroyRootView called
11-16 12:28:43.869  4246  4246 E unknown:ReactInstanceManager: destroyRootView called, unmountReactApplication
11-16 12:28:43.877   691   691 V KeyguardUpdateMonitor: onSubscriptionInfoChanged()
11-16 12:28:43.884   895   895 D Telephony: isEmergencyPreferredAccount: subId=1, activeData=1
11-16 12:28:43.884   895   895 D Telephony: isEmergencyPreferredAccount: Device does not require preference.
11-16 12:28:43.885   691   691 V KeyguardUpdateMonitor: SubInfo:{id=1 iccId=89014103211118510720 simSlotIndex=0 carrierId=1 displayName=T-Mobile carrierName=T-Mobile nameSource=3 iconTint=-16746133 number=+15555215554 dataRoaming=0 iconBitmap=android.graphics.Bitmap@c5919ed mcc=310 mnc=260 countryIso=us isEmbedded=false nativeAccessRules=null cardString=89014103211118510720 cardId=-1 isOpportunistic=false groupUUID=null isGroupDisabled=false profileClass=-1 ehplmns=null hplmns=null subscriptionType=0 groupOwner=null carrierConfigAccessRules=null areUiccApplicationsEnabled=true}
11-16 12:28:44.241   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:45.903   296  5164 I chatty  : uid=1041(audioserver) HwBinder:296_3 identical 29 lines
11-16 12:28:45.949   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:45.957   413   413 I perfetto: probes_producer.cc:329  Producer stop (id=246)
11-16 12:28:45.960   424   424 I perfetto: ng_service_impl.cc:1948 Tracing session 246 ended, total sessions:0
11-16 12:28:45.961   413   413 I perfetto: ftrace_procfs.cc:183    disabled ftrace
11-16 12:28:14.294     0     0 W perfetto: disabled ftrace
11-16 12:28:46.036   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:49.519   296  5164 I chatty  : uid=1041(audioserver) HwBinder:296_3 identical 78 lines
11-16 12:28:49.652   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:28:52.720   471   471 E netmgr  : qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:network' service: Invalid argument
11-16 12:28:52.720   471   471 E netmgr  : Failed to open QEMU pipe 'qemud:network': Invalid argument
11-16 12:28:53.989   296  5164 W android.hardware.audio.service.ranchu: TinyalsaSink::write:125 pcm_write was late reading frames, dropping 22131 us of audio
11-16 12:29:00.006   691   691 D KeyguardClockSwitch: Updating clock: 1229
11-16 12:29:00.596   477   477 E wifi_forwarder: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:wififorward' service: Invalid argument
11-16 12:29:00.596   477   477 E wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
```

**Comment by saghul** [comment] 2022-11-16 06:54
How are you calling getDisplayMedia?

**Comment by Aaronphy** [comment] 2022-11-16 07:57
> How are you calling getDisplayMedia?

just  start  after a foreground service

**Comment by Aaronphy** [comment] 2022-11-22 02:47
> Please show the JS code.
> 
> We don't parse any arguments after gDM is cancelled and I don't see the call to gDM in the backtrace.

Sry for being late to reply, here is the reproduce code.

> register.js

```javascript
import notifee from '@notifee/react-native';

export const initializeApp = () => {
  notifee.registerForegroundService(_notification => {
    return new Promise(() => {});
  });
};

```

> index.js
```javascript
import {AppRegistry} from 'react-native';
import {initializeApp} from './register';
import WebRTCWatch from './App';
import {name as appName} from './app.json';
initializeApp();
AppRegistry.registerComponent(appName, () => WebRTCWatch);

```

> App.js

```javascript
import React, {useEffect, useState} from 'react';
import {StyleSheet, Dimensions, View, Button} from 'react-native';
import {
  RTCPeerConnection,
  RTCSessionDescription,
  RTCIceCandidate,
  RTCView,
  mediaDevices,
} from 'react-native-webrtc';
import notifee, {AndroidImportance} from '@notifee/react-native';
import io from 'socket.io-client';

const screenWidth = Dimensions.get('window').width;
const screenHeight = Dimensions.get('window').height;

export default WebRTCWatch = _ => {

  const [localStream, setLocalStream] = useState();
  const startFgService = async () => {
    try {
      const channelId = await notifee.createChannel({
        id: 'screen_capture',
        name: 'Screen Capture',
        lights: false,
        vibration: false,
        importance: AndroidImportance.DEFAULT,
      });

      await notifee.displayNotification({
        title: 'screen share',
        body: 'screen capturing',
        android: {
          channelId,
          asForegroundService: true,
          pressAction: {
            launchActivity: 'default',
            id: 'default',
          },
        },
      });
    } catch (err) {
      console.log(err);
    }
  };


  const broadcast = async _ => {
    await startFgService();
    const stream =  await mediaDevices.getDisplayMedia();
    setLocalStream(stream);
  };

  return (
    <View style={{flex: 1}}>
      <View style={{flex: 1}}>
        {(localStream && (
          <RTCView
            streamURL={localStream.toURL()}
            zIndex={0}
            objectFit={'cover'}
            style={styles.fullScreen}
          />
        )) || <Button title="Start Share" onPress={_ => broadcast()} />}
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  fullScreen: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: screenWidth,
    height: screenHeight,
  },
});

```

**Comment by saghul** [comment] 2022-11-22 11:36
I see the error going all the way to JS in your trace:

```
11-16 12:28:43.075  4246  4309 I ReactNativeJS: '[get-stream]:error', { name: 'Error',
11-16 12:28:43.075  4246  4309 I ReactNativeJS:   message: 'NotAllowedError',
11-16 12:28:43.075  4246  4309 I ReactNativeJS:   constraintName: undefined }
```

At that point no further callbacks are made into JS. I don't see how this plugin is the cause of that exception, sorry. Can you please to remove the notifee library and give it a try? I think you can sidestep the media projection requirement by targeting Android 8 or 7.

**Comment by Aaronphy** [comment] 2022-11-24 07:36
> I see the error going all the way to JS in your trace:
> 
> ```
> 11-16 12:28:43.075  4246  4309 I ReactNativeJS: '[get-stream]:error', { name: 'Error',
> 11-16 12:28:43.075  4246  4309 I ReactNativeJS:   message: 'NotAllowedError',
> 11-16 12:28:43.075  4246  4309 I ReactNativeJS:   constraintName: undefined }
> ```
> 
> At that point no further callbacks are made into JS. I don't see how this plugin is the cause of that exception, sorry. Can you please to remove the notifee library and give it a try? I think you can sidestep the media projection requirement by targeting Android 8 or 7.

😭，I only have the Android 12 device 。。。

**Comment by saghul** [comment] 2022-11-24 08:12
That is ok, it's the target SDK that matters.

**Comment by Aaronphy** [comment] 2022-12-15 08:06
> That is ok, it's the target SDK that matters.

Android 8 is OK.
And I have a question about  JITSI-MEET ,  how does it use getDisplayMedia without foreground service just like [Notifee](https://notifee.app/react-native/docs/overview) in Android 10+

**Comment by saghul** [comment] 2023-01-12 09:58
We have our own foreground service implementation.

Closing since it doesn't seem to be related to this plugin.

**Closed by saghul** 2023-01-12 09:58 UTC
