### ISSUE TITLE
TypeError: Super expression must either be null or a function, js engine: hermes

### ISSUE THREAD

**Issue by savaliyap** [react-native-webrtc/react-native-webrtc#1530] opened 2024-04-04 05:51 UTC
#### Observed Behavior:

Upon using RTC View, I get the error saying 
TypeError: Super expression must either be null or a function, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

#### Steps to reproduce the issue:

```
import { Alert, Platform, StyleSheet, Text, View } from 'react-native'
import React, { useEffect, useState } from 'react'
import { PERMISSIONS, checkMultiple, request } from 'react-native-permissions';
import {
    MediaStream as AppMediaStream,
    RTCView,
    mediaDevices,
    registerGlobals,
} from "react-native-webrtc";
import { User } from '../models/user.model';
import { CALLSTATUS } from '../constants';
import { VideoCallModelCloseReason } from '../store/slices/types';

type VideoCallModelProps = {
    loggedInUser: User;
    remoteUserId: number;
    onVideoCallModelClose: (reason: VideoCallModelCloseReason) => void
}

const VideoCallModel = ({ loggedInUser, onVideoCallModelClose, remoteUserId }: VideoCallModelProps) => {

    const CAMERA_PERMISSION = Platform.select({
        ios: PERMISSIONS.IOS.CAMERA,
        android: PERMISSIONS.ANDROID.CAMERA,
    });

    const MICROPHONE_PERMISSION = Platform.select({
        ios: PERMISSIONS.IOS.MICROPHONE,
        android: PERMISSIONS.ANDROID.RECORD_AUDIO,
    });

    const [peerConnection, setPeerConnection] = useState(null);
    const [localStream, setLocalStream] = useState<AppMediaStream>(null);
    const [partnerStream, setPartnerStream] = useState<AppMediaStream>(null);

    const checkPermissions = async () => {

        const currentStatus = await checkMultiple([CAMERA_PERMISSION, MICROPHONE_PERMISSION])

        if(currentStatus['android.permission.CAMERA'] === 'denied' || currentStatus['android.permission.CAMERA'] === 'blocked') {
            const cameraStatus = await request(CAMERA_PERMISSION);

            if(cameraStatus !== 'granted') {
                Alert.alert('Please grant camera permission to use Video call feature')
                onVideoCallModelClose(VideoCallModelCloseReason.NO_PERMISSIONS_GRANTED);
                return;
            }
        }

        if(currentStatus['android.permission.RECORD_AUDIO'] === 'denied' || currentStatus['android.permission.RECORD_AUDIO'] === 'blocked') {
            const cameraStatus = await request(MICROPHONE_PERMISSION);

            if(cameraStatus !== 'granted') {
                Alert.alert('Please grant microphone to use Video call feature')
                onVideoCallModelClose(VideoCallModelCloseReason.NO_PERMISSIONS_GRANTED);
                return;
            }
        }
    }

   // Setup here

    useEffect(() => {
        checkPermissions();

        return;
    }, [])

    return (
        <View style={{ flex: 1 }}>
            {/* {localStream != null && <RTCView style={{ width: '100%', height: '100%' }} streamURL={localStream.toURL()} />}
            {partnerStream != null && <RTCView style={{ width: '100%', height: '100%' }} streamURL={partnerStream.toURL()} />}  */}
            {/*  If I uncomment this, I get the error */}
        </View>
    )
}

export default VideoCallModel;

const styles = StyleSheet.create({})
```
        
 

#### Platform Information  
* **React Native Version**: 
```
{
  "name": "",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.21.0",
    "@react-native-community/netinfo": "11.1.0",
    "@react-navigation/material-top-tabs": "^6.6.12",
    "@react-navigation/native": "^6.1.15",
    "@react-navigation/native-stack": "^6.9.24",
    "@reduxjs/toolkit": "^2.2.1",
    "@types/react": "~18.2.45",
    "@types/react-native": "^0.73.0",
    "axios": "^1.6.7",
    "expo": "~50.0.11",
    "expo-constants": "~15.4.5",
    "expo-device": "~5.9.3",
    "expo-linking": "~6.2.2",
    "expo-notifications": "~0.27.6",
    "expo-secure-store": "~12.8.1",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "formik": "^2.4.5",
    "moment": "^2.30.1",
    "react": "18.2.0",
    "react-native": "0.73.4",
    "react-native-pager-view": "6.2.3",
    "react-native-permissions": "^4.1.5",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-vector-icons": "^10.0.3",
    "react-native-webrtc": "^118.0.2",
    "react-redux": "^9.1.0",
    "redux-persist": "^6.0.0",
    "typescript": "^5.3.0",
    "yup": "^1.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

```

* **WebRTC Module Version**: 
* 118.0.2

* **Platform OS + Version**: 
* Android + expo

**Comment by saghul** [comment] 2024-04-04 07:12
Duplicate of https://github.com/react-native-webrtc/react-native-webrtc/issues/1522

**Closed by saghul** 2024-04-04 07:12 UTC
