### ISSUE TITLE
h264 video streaming is not working on selected phones - Failed to set remote offer sdp

### ISSUE THREAD

**Issue by ashwinprasadme** [react-native-webrtc/react-native-webrtc#476] opened 2018-07-06 10:10 UTC
#### Observerd behavior
Webrtc video stream doesn't start with the following error

```
> 07-06 09:45:52.352 E/ReactNativeJS( 9594): 'WebRTC error:', 'Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..'
> 07-06 09:45:52.367 E/unknown:ReactNative( 9594): console.error: "WebRTC error:", "Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..", stack:
```
Detailed logs

[Note 4_2018_7_6_9_57_22.log](https://github.com/oney/react-native-webrtc/files/2169974/app-release-19.apk_2018_7_6_9_57_22.log)

[Note 3.apk_2018_7_6_10_0_59.log](https://github.com/oney/react-native-webrtc/files/2169989/updatedRTC.apk_2018_7_6_10_0_59.log)

This is specific only to devices running 4.4 android it seems, Streaming works great with all other phones and higher android versions.  

#### Expected behavior
i'm attaching some logs where the stream is working well
[Note 8 _2018_7_6_10_7_32.log](https://github.com/oney/react-native-webrtc/files/2170018/updatedRTC.apk_2018_7_6_10_7_32.log)
 for reference

[Galaxy 9_2018_7_6_10_4_43.log](https://github.com/oney/react-native-webrtc/files/2170006/updatedRTC.apk_2018_7_6_10_4_43.log)

#### Update
I noticed that the stream works on samsung tab 4 which is actually running android 4.4. i have attached the log 
[Tab 4_2018_7_6_17_39_37.log](https://github.com/oney/react-native-webrtc/files/2171457/app-release.apk_2018_7_6_17_39_37.log)

#### Platform information

* **React Native version**: 0.50.3
* **Plugin version**: 1.63.0
* **OS**: Android
* **OS version**: v4.4

**Comment by 8BallBomBom** [comment] 2018-08-31 12:01
Are you still having this issue with the latest plugin version?
Not able to reproduce this on the Galaxy S9.

**Comment by iashwinprasada** [comment] 2018-08-31 12:05
Yeah. It works fine on s9. It does not work on pixel phones along with the listed devices above.

**Comment by RangerMauve** [comment] 2018-08-31 13:44
Are you doing any SDP munging? We've got it working fine with h264 on pixel phones. But I think we're using an older version of the library.

**Comment by iashwinprasada** [comment] 2018-08-31 14:05
I'm sorry, it works on pixel phones but not on Nexus 5 and Nexus 7 tab

**Comment by RangerMauve** [comment] 2018-08-31 14:41
Oh, ok. I'll see if we have any of those lying around in case we can reproduce the issue.

**Comment by CSRaghunandan** [comment] 2018-09-06 10:07
@RangerMauve, @8BallBomBom 

We have identified a few more devices on which we getting the SDP error. Below are a full list of devices:
- Nexus 7 tab(v6.0)
- Nexus 9 tab (v5.1)
- Samsung Galaxy s5 (v4.4)
- Nexus 5 (v4.4)
- Samsung Galaxy note 4 (v4.4)
- Samsung Galaxy note 3 (v4.4)
- Samsung Galaxy tab 4 (v4.4)
- Samsung Galaxy j6 (v7.0)
- Kindle fire Gen 1

If you have access to any of these devices, please try to reproduce the issue

**Comment by 8BallBomBom** [comment] 2018-09-07 01:06
Sadly don't have all of them devices.

I have tested these though.
Android 8 - Galaxy s7, Galaxy s8, Galaxy s9
Android 7 - Galaxy Tab A6 10.1
Android 6 - Galaxy s5

So far no issues at all.
If i manage to get any of the other devices i'll test as much as possible.

**Comment by EdoFoco** [comment] 2019-03-03 09:49
Any updates on this issue? I'm having the same problem using Huwawei P10.

**Comment by CSRaghunandan** [comment] 2019-03-03 12:47
@EdoFoco This issue has to fixed on Webrtc upstream.

For now there is no software fallback for H264 decoders and the hardware h264 decoders are always used for h264 streams. So, your stream can fail for two reasons:
1. Your devices hardware h246 decoder is blacklisted by google webrtc
2. The hardware H264 decoder might fail for certain streams due to incompatibility issues.

This is being worked on by the google webrtc engineers, but is not a high priority item. So, might take a while to fix this issue and even longer for it to be backported to react-native-webrtc

**Comment by EdoFoco** [comment] 2019-03-03 17:15
Hi @CSRaghunandan - Thanks for the answer!

Just to be clear, are you saying that react-native-webrtc will not work at all for certain phones? Is there any configuration I can change (e.g. changing h264 to something else)?

It just sounds a bit odd that these many phones won't support webrtc.

Thanks

**Comment by CSRaghunandan** [comment] 2019-03-04 03:34
@EdoFoco If you use VP8/VP9 instead of H264, you should not run into this issue.

**Comment by alex4dev** [comment] 2019-06-25 13:56
Hello,
I know this issue is not very young but i have similar problems and i think its useful for people to be aware of h264 fails on android.

With my Honor10/Android 8.1 i cant finish signaling because h264 codec selected, with vp8 no problems. (i use a Janus sfu server)

This is sad because [Kirin 970](https://en.wikichip.org/wiki/hisilicon/kirin/970) is a recent gpu and can encode/decode h264 but it seems this gpu isnt in google whitelist or the profile level in the offer is bad .
We can see this problem with many huawei/honor phones on the web [here](https://github.com/twilio/twilio-video.js/issues/467), [here ](https://bugs.chromium.org/p/webrtc/issues/detail?id=8538)

So, anybody really use h264 for webrtc with these problems or, like me, you swith to vp8?
vp8 is only sw encode/decode supported on apple world but it works.

**Comment by saghul** [comment] 2019-09-19 08:23
I'm closing this one because there is nothing really actionable.

**Closed by saghul** 2019-09-19 08:23 UTC

**Comment by ThadeusAjayi** [comment] 2020-07-02 09:47
> Hello,
> I know this issue is not very young but i have similar problems and i think its useful for people to be aware of h264 fails on android.
> 
> With my Honor10/Android 8.1 i cant finish signaling because h264 codec selected, with vp8 no problems. (i use a Janus sfu server)
> 
> This is sad because [Kirin 970](https://en.wikichip.org/wiki/hisilicon/kirin/970) is a recent gpu and can encode/decode h264 but it seems this gpu isnt in google whitelist or the profile level in the offer is bad .
> We can see this problem with many huawei/honor phones on the web [here](https://github.com/twilio/twilio-video.js/issues/467), [here ](https://bugs.chromium.org/p/webrtc/issues/detail?id=8538)
> 
> So, anybody really use h264 for webrtc with these problems or, like me, you swith to vp8?
> vp8 is only sw encode/decode supported on apple world but it works.

@alex4dev Kindly guide on how to switch encoder from h264 to vp8 or vp9.

**Comment by tmirun** [comment] 2020-10-09 10:44
some update in this issue?

**Comment by saghul** [comment] 2020-10-09 10:46
There is nothing to update. H.264 may work depending on the device.

**Comment by pettair** [comment] 2021-04-08 19:51
is there a list of these 'blacklisted' decoders (or what would be much better is a list of devices which are supported)?

**Comment by saghul** [comment] 2021-04-08 20:52
Unfortunately not.
