### ISSUE TITLE
NoSuchKeyException sdpMid on Android devices crashes app

### ISSUE THREAD

**Issue by deepakjtrigent** [react-native-webrtc/react-native-webrtc#844] opened 2020-07-30 07:31 UTC
NoSuchKeyException sdpMid occurs on Android devices which crashes the app. Works perfectly on iOS with same iceCandidate but errors out on Android.

According to the webRTC documentation either one of sdpMid or sdpMLineIndex is required and sdpMid is nullable. On the WebRTCModule.java file, sdpMid is accessed and when not present the error occurs and the app crashes. But the same case works fine on iOS. 

D/com.oney.WebRTCModule.WebRTCModule: peerConnectionAddICECandidate() start
E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-2
    Process: com.appName, PID: 30234
    com.facebook.react.bridge.NoSuchKeyException: sdpMid
        at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:137)
        at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:141)
        at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:192)
        at com.oney.WebRTCModule.WebRTCModule.peerConnectionAddICECandidateAsync(WebRTCModule.java:873)
        at com.oney.WebRTCModule.WebRTCModule.lambda$peerConnectionAddICECandidate$17$WebRTCModule(WebRTCModule.java:862)
        at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$pzywRSkn5e14X7FaJ6mZ_hSQiEo.run(Unknown Source:8)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

If I try to handle it from the client end adding an sdpMid: ' ', stream is not received in both Android and iOS.

* **React Native version**: 0.59.9
* **Plugin version**: 1.75.0
* **OS**: iOS

**Comment by Abdelrahman-Nabil** [comment] 2020-11-15 01:04
Did you manage to fix this issue ?

**Comment by iLevye** [comment] 2020-12-22 15:32
Duplicate of #921

**Comment by saghul** [comment] 2020-12-23 10:31
The ice candidate is clearly wrong. The `sdpMid` attribute must have an actual value.

**Closed by saghul** 2020-12-23 10:31 UTC

**Comment by omerts** [comment] 2024-03-13 09:27
@saghul 
> The ice candidate is clearly wrong. The `sdpMid` attribute must have an actual value.
According to docs it can be null:
![image](https://github.com/react-native-webrtc/react-native-webrtc/assets/4996164/407a6bc8-0c37-469c-9c61-890207d6f45c)

https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/sdpMid

**Comment by saghul** [comment] 2024-03-13 09:50
That wasn't the case 4 years ago.

Also, please, stop repeating the same thing on every old issue mentioning this.
