### ISSUE TITLE
Typescript doesn't find `addEventListener`

### ISSUE THREAD

**Issue by gavrilikhin-d** [react-native-webrtc/react-native-webrtc#1488] opened 2023-12-18 05:12 UTC
There is a typescript error, when adding event listeners:
```ts
let pc: RTCPeerConnection = /*...*/;
pc.addEventListener("track", (event) => {});
```
```
error TS2339: Property 'addEventListener' does not exist on type 'RTCPeerConnection'.
```

#### Expected Behavior:

No error

#### Observed Behavior:

Error

#### Steps to reproduce the issue:

1. Create a new RN project (`npx react-native@latest init AwesomeProject`)
2. Install latest webrtc (`npm i react-native-webrtc`)
3. Insert code to add event listener
4. Run lint (`npx tsc`)
5. Get error

#### Platform Information  
* **React Native Version**:  0.73
* **WebRTC Module Version**:  118.0
* **Platform OS + Version**:  Any

**Comment by 8BallBomBom** [comment] 2023-12-18 05:56
Bit of a weird one, didn't experience any issues after all the previous shenanigans which altered ts definitions 🤔 
`RTCPeerConnection` extends `EventTarget` which ensures `addEventListener` is there.
Possibly something has changed in a TypeScript update.

Running `npx tsc` in a previous project isn't giving any errors.
I'll test with a clean project soon.

**Comment by gavrilikhin-d** [comment] 2023-12-18 07:50
> Do you experience any issues doing the following? Without directly giving the type.
> 
> ```ts
> let pc = new RTCPeerConnection();
> ```
Still the same error.

> RTCPeerConnection extends EventTarget which ensures addEventListener is there.
Yes, I can even see it using `find definition` in vscode. However, `RTCPeerConnectionEventMap` is unknown for compiler :(. 
And there are no other type issues, only related to events

**Comment by 8BallBomBom** [comment] 2023-12-18 08:26
Alrighty, thanks for the report, we will address this in an update 👍🏻 
More ts shenanigans 😰

**Comment by gavrilikhin-d** [comment] 2023-12-19 04:20
That is very strange

I've tested it with `yarn run v1.22.21` and it still gives me an error

**Comment by gavrilikhin-d** [comment] 2023-12-19 04:24
Here are screenshots of the error and all the changes from clean project

<img width="723" alt="image" src="https://github.com/react-native-webrtc/react-native-webrtc/assets/75179902/70134ca8-ac80-415c-80ac-4e6ca4d601c8">
`App.tsx`
<img width="584" alt="image" src="https://github.com/react-native-webrtc/react-native-webrtc/assets/75179902/02bc2b97-702a-4323-a192-253af4ff561f">
`package.json`
<img width="351" alt="image" src="https://github.com/react-native-webrtc/react-native-webrtc/assets/75179902/62928b2f-cfe8-49c5-8fb9-53460200b8cb">
`package-lock.json`
<img width="644" alt="image" src="https://github.com/react-native-webrtc/react-native-webrtc/assets/75179902/a2a2f6a3-40b8-4620-83ec-2431f842a56c">

**Comment by 8BallBomBom** [comment] 2023-12-19 04:48
I'll test soime more but so far not managing to reproduce on old and new clean projects 🤔

**Comment by gavrilikhin-d** [comment] 2023-12-19 05:56
I've backported build fix to `react-native-webrtc v113.0.3` and tested with this older version. It still produces typescript error on new RN.

Looks like it's not related to changes made in this library, but rather in changes to typescript configuration in latest RN

**Comment by 8BallBomBom** [comment] 2023-12-19 11:43
If that is the case why am i not experiencing the same error on a new project 🤔 
Either way definitely something we will need to address in an update.

**Comment by gavrilikhin-d** [comment] 2023-12-20 03:51
It may be related to  `event-target-shim`.
One of my colleges has noticed that adding `event-target-shim` as a direct dependency of our project resolves the issue.

He has noticed this warning somewhere:
```
There are types at 'node_modules/event-target-shim/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'event-target-shim' library may need to update its package.json or typings.
```

**Comment by gavrilikhin-d** [comment] 2023-12-21 04:42
Yes, this is caused due-to using `event-target-shim@6.0.2`.
React native is using `event-target-shim@^5.0.1`.

**Comment by gavrilikhin-d** [comment] 2023-12-21 04:43
Related issue: #1466

**Comment by saghul** [comment] 2023-12-21 06:08
Are you using yarn instead of npm?

**Comment by gavrilikhin-d** [comment] 2023-12-21 08:38
I'm using `npm` but the same problem applies to `yarn` too.

**Comment by gavrilikhin-d** [comment] 2023-12-21 08:39
Current workaround:
1. add `event-target-shim@6.0.2` to direct dependency
2. patch it
```
diff --git a/node_modules/event-target-shim/package.json b/node_modules/event-target-shim/package.json
index 045cf8b..8f8faaa 100644
--- a/node_modules/event-target-shim/package.json
+++ b/node_modules/event-target-shim/package.json
@@ -3,18 +3,6 @@
   "version": "6.0.2",
   "description": "An implementation of WHATWG EventTarget interface.",
   "main": "index.js",
-  "exports": {
-    ".": {
-      "import": "./index.mjs",
-      "require": "./index.js"
-    },
-    "./es5": {
-      "import": "./es5.mjs",
-      "require": "./es5.js"
-    },
-    "./umd": "./umd.js",
-    "./package.json": "./package.json"
-  },
   "files": [
     "index.*",
     "es5.*",
```

**Comment by saghul** [comment] 2023-12-21 10:21
Weird. Our package uses a more recent version of that package than RN itself, but the RN dependency hasn't changed so I'm not entirely sure why you get that problem now.

**Comment by 8BallBomBom** [comment] 2023-12-21 12:25
> I'm using `npm` but the same problem applies to `yarn` too.

Tried the same, also same result, no errors on this side 🤔 really having a hard time accomplishing reproduction...

> Weird. Our package uses a more recent version of that package than RN itself, but the RN dependency hasn't changed so I'm not entirely sure why you get that problem now.

My thought exactly 😨

**Comment by gavrilikhin-d** [comment] 2023-12-24 16:20
I have create a docker image that can reproduce the bug
https://hub.docker.com/repository/docker/gavrilikhind/react-native-webrtc-ts-bug-repro/general

**Comment by gavrilikhin-d** [comment] 2023-12-25 13:28
@8BallBomBom are you able to reproduce the issue on docker?

**Comment by 8BallBomBom** [comment] 2023-12-25 13:35
Haven't tested yet but i will have a check and get back to you within a few days 👍🏻 
Happy Holidays 🎄

**Comment by gavrilikhin-d** [comment] 2023-12-25 13:57
Happy Christmas! 🎄 🤶

**Comment by danibalcr** [comment] 2024-01-01 21:53
Hello, I have the same problem too.

```
peerConnection.current.addEventListener('ontrack', event => {
    setRemoteStream(event.stream);
  });

or

peerConnection.current.ontrack = event => {
    setRemoteStream(event.stream);
  };

or

peerConnection.current.onicecandidate = event => {};
```
<img width="988" alt="Screenshot 2024-01-01 at 17 52 29" src="https://github.com/react-native-webrtc/react-native-webrtc/assets/52415902/17849538-3330-452b-aebd-2adfc6bf0311">

**Comment by danibalcr** [comment] 2024-01-01 21:55
My React Native Info is:

```
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1
  Memory: 175.97 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.13.0
    path: ~/.nvm/versions/node/v18.13.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.19.3
    path: ~/.nvm/versions/node/v18.13.0/bin/npm
  Watchman:
    version: 2023.09.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.0
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "23"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-31 | ARM 64 v8a
      - android-31 | Google APIs ARM 64 v8a
      - android-31 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.8
    path: /Users/[user_name]/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

**Comment by danibalcr** [comment] 2024-01-01 22:14
> Current workaround:
> 
> 1. `npm i event-target-shim@6.0.2`
> 2. patch it with `npx patch-package event-target-shim  --exclude 'nothing'`
> 
> ```diff
> diff --git a/node_modules/event-target-shim/package.json b/node_modules/event-target-shim/package.json
> index 045cf8b..8f8faaa 100644
> --- a/node_modules/event-target-shim/package.json
> +++ b/node_modules/event-target-shim/package.json
> @@ -3,18 +3,6 @@
>    "version": "6.0.2",
>    "description": "An implementation of WHATWG EventTarget interface.",
>    "main": "index.js",
> -  "exports": {
> -    ".": {
> -      "import": "./index.mjs",
> -      "require": "./index.js"
> -    },
> -    "./es5": {
> -      "import": "./es5.mjs",
> -      "require": "./es5.js"
> -    },
> -    "./umd": "./umd.js",
> -    "./package.json": "./package.json"
> -  },
>    "files": [
>      "index.*",
>      "es5.*",
> ```

This worked for me

**Comment by 8BallBomBom** [comment] 2024-01-02 11:06
Thanks for the update, will be checking over everything soon 😸 
Definitely some undesired behaviour going on.

**Comment by gavrilikhin-d** [comment] 2024-01-20 07:44
The image is basically node container for template react app with react-native-webrtc added. You can try to create it yourself, if there are problems with my image

**Comment by 8BallBomBom** [comment] 2024-01-20 07:54
Might be easier to debug if you can provide the project files directly and some info about the environment you are using that is experiencing the issue. For some reason when building the image i'm getting a lot of weirdness with buildkit 🤦🏻

**Comment by cubase** [comment] 2024-01-22 12:39
Find out that problem is caused by changes in RN base `tsconfig.json` which you use in extends param. Overriding `compilerSettings` fixed this problem for me:

tsconfig.json
```
"extends": "@react-native/typescript-config/tsconfig.json",
"compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    }
  }
```

**Comment by santhoshvai** [comment] 2024-01-25 19:34
From my test, This occurs on newer RN, specifically in RN 0.73 where the metro has been upgraded to have stable symlink support. 

Newer Metro, prefers `event-target-shim@^5.0.1` used by RN than `event-target-shim@6.0.2` that is needed by the webrtc library. Perhaps, this is because event-target-shim@^5.0.1 is hoisted? 

I was able to workaround this from the metro config using the config below

```
const rnWebrtcPath = path.resolve(
  projectRoot,
  'node_modules/react-native-webrtc',
);

// match event-target-shim from this path
const extraNodeModules = {
  'event-target-shim': path.resolve(
    rnWebrtcPath,
    'node_modules/event-target-shim',
  ),
};

// block event-target-shim paths that do not match a path starting with react-native-webrtc path
const blockList = [
  new RegExp(`(?<!${rnWebrtcPath})/node_modules/event-target-shim`),
];

config.resolver.extraNodeModules = extraNodeModules;

config.resolver.blockList = blockList;

module.exports = config;
```

**Comment by 8BallBomBom** [comment] 2024-02-01 09:14
As mentioned in the linked issue ^ we're investigating and looking to privide a fix for this issue shortly 🤔

**Comment by b0iq** [comment] 2024-03-25 21:25
> As mentioned in the linked issue ^ we're investigating and looking to provide a fix for this issue shortly 🤔

Any updates?

**Comment by saghul** [comment] 2024-03-25 21:48
A workaround landed in master and will be part of the next release.

**Comment by 8BallBomBom** [comment] 2024-03-26 04:12
Forgot we had multiple issues resolved by the same pr 🤦🏻
Should be resolved by the next update.

**Closed by 8BallBomBom** 2024-03-26 04:12 UTC
Labels: bug, confirmed, needs-research

**Comment by EmpiteNishain** [comment] 2024-04-01 04:53
I don't know how but after changing the .tsconfig like this it worked

```{
  "compilerOptions": {
    "allowJs": true,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "jsx": "react",
    "lib": ["es6"],
    "moduleResolution": "node",
    "noEmit": true,
    "strict": true,
    "target": "esnext"
  },
  "exclude": [
    "node_modules",
    "babel.config.js",
    "metro.config.js",
    "jest.config.js",
    "*.svg"
  ]
}

**Comment by bujhmt** [comment] 2024-04-01 07:03
> I don't know how but after changing the .tsconfig like this it worked
> 
> ```
>   "compilerOptions": {
>     "allowJs": true,
>     "resolveJsonModule": true,
>     "allowSyntheticDefaultImports": true,
>     "esModuleInterop": true,
>     "isolatedModules": true,
>     "jsx": "react",
>     "lib": ["es6"],
>     "moduleResolution": "node",
>     "noEmit": true,
>     "strict": true,
>     "target": "esnext"
>   },
>   "exclude": [
>     "node_modules",
>     "babel.config.js",
>     "metro.config.js",
>     "jest.config.js",
>     "*.svg"
>   ]
> }
> ```

Hello, I suppose you only need `allowSyntheticDefaultImports` option for fix, like this:
```
  "compilerOptions": {
    "allowSyntheticDefaultImports": true
  },
```
You can check more [here](https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports), but the long story short - it's problem with imports inside library.

**Comment by 8BallBomBom** [comment] 2024-04-01 13:30
Interesting simpler fix 🤔
