### ISSUE TITLE
Receive Only: Cannot read property 'codecs' of undefined

### ISSUE THREAD

**Issue by TheRealNate** [react-native-webrtc/react-native-webrtc#1301] opened 2023-01-30 05:04 UTC
Hi there!

I'm trying to use this package in order to view the stream of nest cameras from the Nest SDM API. This API allows viewing these streams using receive only WebRTC.

I'm getting this error:

````
 ERROR  TypeError: Cannot read property 'codecs' of undefined, js engine: hermes
````

And here is my code:

      const connection = new RTCPeerConnection({iceServers: []});

      connection.createDataChannel('dataSendChannel');

      const offer = (await connection.createOffer({
        offerToReceiveAudio: true,
        offerToReceiveVideo: true,
      })) as RTCSessionDescription;

      if (offer.sdp != null) {
        await connection.setLocalDescription(offer);

        console.log(offer.sdp);
        void callTheNestAPIWithMyOfferAndGetBackAnAnswerSDP()
          .then(res => {
            void connection.setRemoteDescription({
              sdp: res.answerSdp,
              type: 'answer',
            });
          });
      }

The error is thrown when calling `connection.setRemoteDescription()`.

I've traced it back to `src/RTCRtpParameters.ts`, where the constructor expects to have an object and doesn't receive it.

Also strangely, when this error occurs, I hear my own audio feeding back from the test device.

Here is my answer SDP:

````
v=0
o=- 0 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 2 1
a=msid-semantic: *****
a=ice-lite
m=audio 19305 UDP/TLS/RTP/SAVPF 111
c=IN IP4 *****
a=rtcp:9 IN IP4 0.0.0.0
a=candidate: *****
a=candidate: *****
a=candidate: *****
a=candidate: *****
a=candidate: *****
a=candidate: *****
a=ice-ufrag:*****
a=ice-pwd:*****
a=fingerprint:sha-256 *****
a=setup:passive
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendrecv
a=msid:virtual-6666 virtual-6666
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=ssrc:6666 cname:6666
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:*****
a=ice-pwd:*****
a=fingerprint:sha-256 *****
a=setup:passive
a=mid:1
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendrecv
a=msid:*****
a=rtcp-mux
a=rtpmap:96 H264/90000
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=*****
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 H264/90000
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtcp-fb:98 goog-remb
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=*****
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=ssrc-group:FID ***** *****
a=ssrc:***** cname:*****
a=ssrc:***** cname:*****
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:*****
a=ice-pwd:*****
a=fingerprint:sha-256 *****
a=setup:passive
a=mid:2
a=sctpmap:5000 webrtc-datachannel 1024
````

**Comment by saghul** [comment] 2023-01-30 07:29
Feels like a duplicate of https://github.com/react-native-webrtc/react-native-webrtc/issues/1292

**Closed** 2023-01-30 07:30 UTC

**Comment by saghul** [comment] 2023-01-30 10:42
Please see: https://github.com/react-native-webrtc/react-native-webrtc/issues/1292#issuecomment-1408386377
