### ISSUE TITLE
Dependency org.jitsi:webrtc cannot be resolved due to https://oss.sonatype.org downtime

### ISSUE THREAD

**Issue by GreenGraphicx1** [react-native-webrtc/react-native-webrtc#1653] opened 2024-12-11 10:36 UTC
The dependency org.jitsi:webrtc, which is required by react-native-webrtc, cannot be resolved because the Maven repository at https://oss.sonatype.org is currently unavailable (504 Gateway Timeout).

**Steps to Reproduce:**
1. Attempt to build the project using `react-native-webrtc`.
2. Observe the error regarding the unresolved dependency.

**Error Logs:**
Failed to list versions for org.jitsi:webrtc. Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/org/jitsi/webrtc/maven-metadata.xml'. Received status code 504.
markdown
Copy code

**Impact:**
This prevents builds from completing successfully. Please consider hosting the dependency in a more reliable Maven repository or providing an alternative solution.

**Environment:**
- `react-native-webrtc` version: [Specify]
- React Native version: [Specify]
- Expo SDK version: [Specify, if applicable]
- Platform: Android

Thank you for looking into this!

**Comment by saghul** [comment] 2024-12-11 10:52
Duplicate of https://github.com/react-native-webrtc/react-native-webrtc/issues/1652

That's Macen Central, we don't control it. It's likely a transient issue.

**Closed** 2024-12-11 10:52 UTC
