### ISSUE TITLE
dataChannelDidChangeState crash in ios when connect to remote peers

### ISSUE THREAD

**Issue by PhoenixInnovate** [react-native-webrtc/react-native-webrtc#965] opened 2021-04-07 09:45 UTC
#### Platform information

* **React Native version**:
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by saghul** [comment] 2021-04-07 09:49
Please search existing issues before opening a new one. Closing as a duplicate of https://github.com/react-native-webrtc/react-native-webrtc/issues/962

**Closed by saghul** 2021-04-07 09:49 UTC
