### ISSUE TITLE
Unimplemented component: <RTCVideoView>

### ISSUE THREAD

**Issue by asthapatel3020** [react-native-webrtc/react-native-webrtc#1281] opened 2023-01-12 19:50 UTC
I am able to get the local stream but when I run the app it throws 'Unimplemented component: <RTCVideoView>' in iOS. All the settings for video streaming work fine in android. 

![simulator_screenshot_304049A2-C32C-4862-8BE4-770485ECC83D](https://user-images.githubusercontent.com/42024843/212166029-df25b882-6afd-4bc0-8f3a-11436b7343d5.png)

#### Expected Behavior

Need to load a local stream in iOS

#### Observed Behavior

Getting local stream correctly

`{ active: true,
  _tracks: 
   [ { _constraints: {},
       _enabled: true,
       _settings: {},
       _muted: false,
       id: '490E1D4F-445B-440F-B828-403C88105086',
       kind: 'audio',
       label: '490E1D4F-445B-440F-B828-403C88105086',
       remote: false,
       readyState: 'live' },
     { _constraints: { facingMode: 'user', frameRate: 30, height: 720, width: 1280 },
       _enabled: true,
       _settings: { height: 0, frameRate: 3, width: 0 },
       _muted: false,
       id: '9D7F8B39-7B95-4B2E-B74F-6EF9B77B19EE',
       kind: 'video',
       label: '9D7F8B39-7B95-4B2E-B74F-6EF9B77B19EE',
       remote: false,
       readyState: 'live' } ],
  id: 'E1569DE5-4D24-4112-A376-35931B175C42',
  _reactTag: 'E1569DE5-4D24-4112-A376-35931B175C42' }`

#### Platform Information

* **React Native Version**: 0.70.6
* **Plugin Version**: ^1.94.1
* **OS**:  iOS | macOS
* **OS Version**: macOS Monterey (12.4) (m1-chip)

**Comment by asthapatel3020** [comment] 2023-01-12 20:25
@saghul 
Please help me out with this asap. 
  {localStream && (
        <RTCView
          streamURL={localStream?.toURL()}
          zOrder={1}
          style={{
            height: '100%',
          }}
        />
      )}

**Comment by saghul** [comment] 2023-01-12 21:37
Looks like the plugin wasn't linked properly or something similar.

**Comment by asthapatel3020** [comment] 2023-01-12 21:41
I followed all the steps.
- Install npm i react-native-webrtc
- cd ios/ pod install
- added permission in Info.plist
Still getting this.

**Comment by 8BallBomBom** [comment] 2023-01-12 22:32
Make sure you don't have the new architecture forced on.
As the new architecture has started maturing we will need to work on migration at some point.

**Comment by asthapatel3020** [comment] 2023-01-16 15:24
@8BallBomBom Thank you. I was installing a pod using the new architecture. When I disable the new arch I am able to load a video. 

But there is one issue I am not able to access the remote stream using RTCPeerConnection. Here is a code :

` let peerConstraints = {
    iceServers: [
      {
        urls: 'stun:stun.l.google.com:19302',
      },
    ],
  };
  const peerConnection = new RTCPeerConnection();
   if (peerConnection) {
      if (newStream) {
        peerConnection.addStream(newStream); //newStream is a local stream
      }
      peerConnection.addEventListener("addstream", event => {
        setRemoteStream(event.stream);
      });
      peerConnection.addEventListener( "icecandidate", event => {
        if ( !event.candidate ) { return; };
        console.log("localPC icecandidate:", e.candidate);
          socket.emit("iceCandidate", event.candidate);
      } );
    }

  `

**Comment by saghul** [comment] 2023-01-16 18:45
Let's keep each issue focused. This one is solved som I'm closing it.

When reporting "I can the remote" type of issues note we won't be able to reproduce your problem so be as detailed as possible and make sure you understand whether you need TURN and STUN or not.

**Closed** 2023-01-16 18:45 UTC
