### ISSUE TITLE
expo TypeError: Cannot read property 'senderGetCapabilities' of null, js engine: hermes

### ISSUE THREAD

**Issue by galaxy-s10** [react-native-webrtc/react-native-webrtc#1466] opened 2023-10-30 04:57 UTC
When I Import This statements

```js
import {  RTCPeerConnection } from 'react-native-webrtc';
```
The error Come in my expo Go(In android mobile)

```
 ERROR  TypeError: Cannot read property 'senderGetCapabilities' of null, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

But If I not Import react-native-webrtc then it run smoothly

I need to create functionality which uses webrtc

package.json:
```
{
  "name": "billd-live-react-native",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@config-plugins/react-native-webrtc": "^7.0.0",
    "@react-navigation/bottom-tabs": "^6.5.10",
    "@react-navigation/native": "^6.1.9",
    "@rneui/base": "4.0.0-rc.8",
    "@rneui/themed": "4.0.0-rc.8",
    "axios": "^1.5.1",
    "expo": "~49.0.15",
    "expo-av": "^13.4.1",
    "expo-camera": "^13.4.4",
    "expo-dev-client": "~2.4.11",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-reanimated": "^3.5.4",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.1",
    "react-native-webrtc": "111.0.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "typescript": "^5.1.3"
  },
  "private": true
}

```

#### Platform Information  
* **React Native Version : 0.72**
* **WebRTC Module Version：111.0.6**
* **Platform OS + Version ：Expo**

**Comment by robertbarclay** [comment] 2023-10-30 22:10
getting something similar. This seems to have to do with `event-target-shim`, and it appears to be with the 111.0.6 update as best as i can tell, since its a new issue than to the 111.0.4 version with the missing onXXX handlers. I get similar but different failures, something along the lines of:

```
TypeError: Cannot call a class as a function, js engine: hermes
TypeError: Cannot read property 'render' of undefined, js engine: hermes
TypeError: Cannot call a class as a function, js engine: hermes
TypeError: Cannot read property 'prototype' of undefined, js engine: hermes
```

We have several dependencies that pull `event-target-shim ^5.0.1` and this library which is pulling `6.0.2`, where there are breaking changes between the two versions, seems like there might be an issue. 

`defineEventAttribute` has been marked deprecated, yet it was added for each of the EventTarget's Event Map items in the 111.0.6 release. its recommended to move to `setEventAttributeValue` function in that library on the documentation for that method.

**Comment by saghul** [comment] 2023-10-31 08:22
> We have several dependencies that pull `event-target-shim ^5.0.1` and this library which is pulling `6.0.2`, where there are breaking changes between the two versions, seems like there might be an issue.

6.0.2 was released a long time ago, what is the reason not to update?



> `defineEventAttribute` has been marked deprecated, yet it was added for each of the EventTarget's Event Map items in the 111.0.6 release. its recommended to move to `setEventAttributeValue` function in that library on the documentation for that method.

That was deprecated in v6, I suspect you don't see deprecation warnings since you might be on v5.



> TypeError: Cannot call a class as a function, js engine: hermes
> TypeError: Cannot read property 'render' of undefined, js engine: hermes
> TypeError: Cannot call a class as a function, js engine: hermes
> TypeError: Cannot read property 'prototype' of undefined, js engine: hermes

All this sounds like Hermes not supporting some JS feature we use. Accessing the class prototype maybe?

If there is a simple fix I'll take it though. I explicitly avoided `setEventAttributeValue` because it would be very verbose, we'd need 2 functions for each event, versus 1 line.

**Comment by robertbarclay** [comment] 2023-10-31 14:25
Given the Hermes is becoming the default on RN, would it be a good idea then to support Hermes if .prototype is infact not supported?

**Comment by robertbarclay** [comment] 2023-10-31 14:34
we are currently using RN 0.72.5. 

Per https://reactnative.dev/docs/hermes, it has become dafault as of RN 0.70

and RN 0.72.5 has `event-target-shim` at '^5.0.1', which is why we have not moved to 6.0.2. Not sure why they have not updated, bug given that there were breaking changes between 5.x and 6.x, seem like they are resisting the update on thier side, even though it was released a while ago.

**Comment by saghul** [comment] 2023-10-31 15:32
Oh, I see, I thought it wasn't the default yet.

I suppose trying out the `setEventAttributeValue` is a decent way forward without much churn, would you like to give it a try? I won't have cycles to do that in the upcoming weeks. I want to finish M118 support first.

**Comment by robertbarclay** [comment] 2023-10-31 16:00
Will see what we can do. We have some tight cycles as well.

**Comment by 8BallBomBom** [comment] 2023-10-31 16:50
I'll have a bash at this and put a draft pr up soon 👍🏻 
Feel kinda obliged as some stuff fell between the cracks on my watch 😅

**Comment by robertbarclay** [comment] 2023-11-01 16:06
I might have found more information to help with this issue:

basically RN 0.72.x is still using `event-target-shim: "^5.0.1"`. We are using yarn in a learna mono repo, so under `react-native-webrtc`'s node_modules folder, we are correctly seeing `event-target-shim` 6.0.2, and up in our root node_module folder we are seeing v5.0.0. normally this should not be an issue, but given possibly our configuration of webpack and/or hermes, it seems the may be flattening it down to one, and that may be 5.0.0.

the net result is Event and EventTarget in this setup, and it may be the same for expo, does not the `EventTarget` and `Event` defined in the 6.0.2 version due to the breaking change, so we are getting issues. At this point i do not thing the prototypes is the issue, but rather its not even a class, so when we ask for the prototype, its not a class since in the prior viersion it was just a function. We then see all the above issue.

if i try to set the resolution in the root package.json to be 6.0.2, funcitons in react native break, and we get the 
> TypeError: Cannot call a class as a function, js engine: hermes
> TypeError: Cannot read property 'render' of undefined, js engine: hermes
> TypeError: Cannot call a class as a function, js engine: hermes
> TypeError: Cannot read property 'prototype' of undefined, js engine: hermes
for classes that are NOT in the `reaact-native-webrtc` module. 

if i do not set any resolutions, so the respective node_modules have thier version of `event-target-shim` set, then i get 
> [TypeError: Super expression must either be null or a function]

which through the process of elimination, have come to determine it is not seeing the Event class as defined up in the 6.0.2 version of `event-target-shim`, becasue we get a failure on the `MediaStreamTrackEvent.ts` from an import of the `react-native-webrtc` module from the index.ts. For us, since we call the `registerGlobals()` function in our own pollyfill.ts file, its dumps out there. If i remove all affiliation to Event from the class, the issue moves on to the RTCEvent error, whcih is the next thing to be exported that extends the Event object from the index.js.... so it follows the pattern.

That is where i am thus far in debugging the problem, if that helps.

**Comment by robertbarclay** [comment] 2023-11-01 16:35
By removing all imports of `Event` and implementing the `type` prop on each Event subclass class (in a hacky way) i was able to get these errors to disappear given my hunch above with the flattening of the two modules. working up a better less hacky way to propose a patch for this, but that is my progress thus far.

**Comment by saghul** [comment] 2023-11-02 09:29
> basically RN 0.72.x is still using `event-target-shim: "^5.0.1"`. We are using yarn in a learna mono repo, so under `react-native-webrtc`'s node_modules folder, we are correctly seeing `event-target-shim` 6.0.2, and up in our root node_module folder we are seeing v5.0.0. normally this should not be an issue, but given possibly our configuration of webpack and/or hermes, it seems the may be flattening it down to one, and that may be 5.0.0.

Are you able to confirm this? The errors don't suggest that, do they? We should see import errors I think no?

> At this point i do not think the prototypes is the issue, but rather its not even a seen as a class

It was a class in both versions IIRC.



> By removing all imports of `Event` and implementing the `type` prop on each Event subclass class (in a hacky way) i was able to get these errors to disappear given my hunch above with the flattening of the two modules. working up a better less hacky way to propose a patch for this, but that is my progress thus far.

Hum, that is a good find indeed. I'm not sure what to do here TBH. Any system that flattens out dependencies with differring major versions is simply asking for trouble. If a library needs v6 and the core RN uses v5 so be it, it's just a few KB, picking one and hoping things work is plain wrong.

**Comment by 8BallBomBom** [comment] 2023-11-02 11:39
Not entirely sure how to proceed, we could downgrade the package and make any adjustements as needed but then as soon as other packages upgrade we will be back here having to potentially make changes again 🤔

**Comment by robertbarclay** [comment] 2023-11-02 12:31
i'm seeing if there are adjustments that can/need to be made with webpack and our bunlding proccess, becuase it would be a serious issue of flattening out two differing versions of a library with breaking changes.

I'm attempting to create a superclass of the Events, that then could do some inspection to determine if there is an issue with  EVENT subclassing, and fix accordingly. The events class could then subclass that, and maybe that might resolve the issue. Will see where I get today on it.

**Comment by robertbarclay** [comment] 2023-11-03 20:23
As an update here, we found that we has some bable preset configurations that was flattening our modules out as an optimization, and due to that the `event-target-shim` that was being used across our project was the version 5.0.0 of this, rather than 6.0.2, so everywhere we looked we kept running into issues.  basically Event was a function in 5.0.0, and a defined abstract class in 6.0.2, so when the extends was used, it broke, any way you looked at it, anywhere along the import tree, if you imported any part of `react-native-webrtc` it would break first in events, and then when the events wend to dispatch it would break on the dispatch, etc. Good game a whack a mole till we figued out is was the wrong code trying tu be ran all thogether.

Maybe this will help were others may have done the same, and might face the same issue. It was a good head scratcher. both libraries for the time being need to coexist in the project due to react native being pinned to the older version.

i'm all for updating away from deprecated methods and adding better typing, and will see where we can contribute on that font going forward. Thank you guys for looking into this issue, and digging and all the effort that goes into maintaining this piece of code.

**Comment by saghul** [comment] 2023-11-03 23:00
Thanks for sharing!

**Comment by 8BallBomBom** [comment] 2023-11-04 06:28
The pr should be alright to merge, as for the weird typing errors, something to check/improve in future 🤔

**Comment by 8BallBomBom** [comment] 2024-03-26 04:18
Should be fixed when the next update goes out 👍🏻 
Many duplicate/similar issues caused by the same thing 😅

**Closed by 8BallBomBom** 2024-03-26 04:18 UTC
Labels: duplicate, confirmed
