### ISSUE TITLE
When connecting two local PeerConnections with a DataChannel: uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]' *** First throw call stack:

### ISSUE THREAD

**Issue by ibc** [react-native-webrtc/react-native-webrtc#971] opened 2021-04-21 10:16 UTC
The following sample code (it communicates two local PeerConnections by creating a DataChannel) crashes on iOS, it can be reproduced in simulator of iOS 14.4):

```ts
const pc1 = new RTCPeerConnection();
const pc2 = new RTCPeerConnection();

pc1.createDataChannel('foo', { ordered: true });

pc1.addEventListener('icecandidate', event => {
  const candidate = event.candidate;

  if (candidate) {
    pc2.addIceCandidate(candidate);
  }
});

pc2.addEventListener('icecandidate', event => {
  const candidate = event.candidate;

  if (candidate) {
    pc1.addIceCandidate(candidate);
  }
});

const offer = await pc1.createOffer();

await pc1.setLocalDescription(offer);
await pc2.setRemoteDescription(offer);

const answer = await pc2.createAnswer();

await pc2.setLocalDescription(answer);
await pc1.setRemoteDescription(answer); // <-- Crash happens here!
```

Crash:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2049d77f _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff204a8ec4 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.5 + 0
	4   CoreFoundation                      0x00007fff2048bcb7 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 235
	5   CoreFoundation                      0x00007fff2041f773 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 49
	6   mobileapp-stage                     0x000000010b33155a -[WebRTCModule(RTCDataChannel) dataChannelDidChangeState:] + 282
	7   WebRTC                              0x000000010da3cbef _ZN6webrtc26DataChannelDelegateAdapter13OnStateChangeEv + 89
	8   WebRTC                              0x000000010de8976a _ZN6webrtc15SctpDataChannel8SetStateENS_20DataChannelInterface9DataStateE + 40
	9   WebRTC                              0x000000010de898b4 _ZN6webrtc15SctpDataChannel11UpdateStateEv + 282
	10  WebRTC                              0x000000010de8b289 _ZN6webrtc23webrtc_new_closure_impl11ClosureTaskIZNS_15SctpDataChannel4InitEvE3$_1E3RunEv + 25
	11  WebRTC                              0x000000010da7e285 _ZN3rtc6Thread17QueuedTaskHandler9OnMessageEPNS_7MessageE + 39
	12  WebRTC                              0x000000010da7da4b _ZN3rtc6Thread8DispatchEPNS_7MessageE + 143
	13  WebRTC                              0x000000010da7c952 _ZN3rtc6Thread15ProcessMessagesEi + 140
	14  WebRTC                              0x000000010da7de92 _ZN3rtc6Thread6PreRunEPv + 76
	15  libsystem_pthread.dylib             0x00007fff60c8e109 _pthread_start + 148
	16  libsystem_pthread.dylib             0x00007fff60c89b8b thread_start + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
terminating with uncaught exception of type NSException
```

#### Expected behavior

Do not crash.

#### Observerd behavior

It crashes.

#### Steps to reproduce the problem

Code above.

#### Platform information

* **React Native version**: 0.63.4
* **Plugin version**: 1.89.1
* **OS**: iOS 14.3 (simulator of iOS 14.4)

**Comment by ibc** [comment] 2021-04-21 10:50
This can be unrelated, but I fail to understand this code in `WebRTCModule+RTCPeerConnection.m`:

```objc
RCT_EXPORT_METHOD(peerConnectionCreateAnswer:(nonnull NSNumber *)peerConnectionId
                                     options:(NSDictionary *)options
                                    callback:(RCTResponseSenderBlock)callback)
{
  RTCPeerConnection *peerConnection = self.peerConnections[peerConnectionId];
  if (!peerConnection) {
    return;
  }

  // ...
```

So basically, if `peerConnectionId` does not exist, this method will return null or undefined or whatever. Then in JS land we are gonna resolve with `resolve(new RTCSessionDescription(data))`. Anyway this cannot be the problem AFAIS.

Also unrelated: `RTCSessionDescription` class no longer exists in the spec nor in . It must be just an object with `type` and `sdp`.

**Comment by saghul** [comment] 2021-04-21 11:53
The bug is in dataChannelDidChangeState. This is a duplicate of https://github.com/react-native-webrtc/react-native-webrtc/issues/962 -- Can you please post your example there?

**Closed by saghul** 2021-04-21 11:53 UTC

**Comment by ibc** [comment] 2021-04-21 11:59
Done
