### ISSUE TITLE
Asking about a warning appeared in the latest beta 

### ISSUE THREAD

**Issue by qusaieilouti99** [react-native-webrtc/react-native-webrtc#1237] opened 2022-11-23 10:55 UTC
i'm trying to perform the perfect negotiation concept and when I update the package to the beta I'm now receiving this warning.
i just wanna know what is it and if its important to care about?

`Sending "peerConnectionOnRenegotiationNeeded" with no listeners registered.`

**Comment by 8BallBomBom** [comment] 2022-11-23 16:25
Shouldn't be of any concern.
But also have you got the `negotiationneeded` event attached to your peer connection?

```javascript
peerConnection.addEventListener( 'negotiationneeded', event => {

} );
```

Generally a good event to use for creating offers.
Can read more about it over [here](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/negotiationneeded_event).

**Comment by qusaieilouti99** [comment] 2022-11-23 17:47
sometimes the call on ios gives a black screen and last thing I get is this warning, although I do have the listener. also, the issue doesn't happen all the time so it's hard to debug for me. Also, sometimes I get a warning, but the call works fine but when it doesn't work, the last thing I get is this warning so the call doesn't continue to the negotiation needed listeners and other listeners ... so that's why I am asking about this warning. Are you sure this doesn't cause a problem?

I see this warning on ios only, also the issue happens to ios only.

**Comment by saghul** [comment] 2022-11-23 18:32
Are you closing the PC at any point?

**Comment by qusaieilouti99** [comment] 2022-11-23 18:39
Only when the call finished I'm closing all the connections or when one of the peers leaves the call I close the connection with him

**Comment by saghul** [comment] 2022-11-24 08:17
Does this warning show up at that point exactly?

**Comment by qusaieilouti99** [comment] 2022-11-24 10:49
no it show up when creating a peer connection like in signaling part

**Comment by saghul** [comment] 2022-11-24 11:32
That's kind of odd since we add a listener to that event on the PC creation.

What version are you running exactly and  what platform do you see this?

**Comment by qusaieilouti99** [comment] 2022-11-24 11:39
I'm was using latest beta verison but once you fixed the perfect negotiation I switched to the branch 
 "react-native-webrtc": "github:react-native-webrtc/react-native-webrtc.git#c9f3dee20d2e5faa87eb5a50d29bec69522817d4", 
 Platfprm:IOS
 react native version: "0.67.2"

**Comment by saghul** [comment] 2022-11-24 12:00
The only related thing that comes to mind is this: https://github.com/react-native-webrtc/react-native-webrtc/commit/19c0a12820832d3715d4ab286170828fe6bf6ea7 but that was a while ago, and it happened only during close.

**Comment by qusaieilouti99** [comment] 2022-11-24 12:20
but it does happen sometimes when i first get into the app, meaning on the first call.
so no connections get closed yet

**Comment by saghul** [comment] 2022-11-24 12:47
We register to that event here: https://github.com/react-native-webrtc/react-native-webrtc/blob/e903b3133c9c8fd0c56651f889f0f8d08fcc0ba9/src/RTCPeerConnection.ts#L81 https://github.com/react-native-webrtc/react-native-webrtc/blob/e903b3133c9c8fd0c56651f889f0f8d08fcc0ba9/src/RTCPeerConnection.ts#L453

Since that is called in the constructor, I'm not sure how you can end up unregistered from that event.

Do you have handler for the PC connection state and ICE connection state? If not, can you add them and log the state they change to?

**Comment by qusaieilouti99** [comment] 2022-11-24 13:38
i do have the handlers actually, but when this issue happens the handlers doesn't log anything. all the listeners doesn't work even the "onnegotiationneeded". like it crashes the connection.

the weird thing it only happens to IOS

**Comment by saghul** [comment] 2022-11-24 14:44
What do you mean by "crashes" ? What ICE and connection state changes do you get?

**Comment by qusaieilouti99** [comment] 2022-11-24 14:46
I mean its stopping the connection because I don't get any connection state or ice state or even onnegotiationneeded

**Comment by saghul** [comment] 2022-11-24 14:47
Please share the code you are using and the logs from the Xcode console. I suspect something is going on very early and the PC is not properly initialized or something...

**Comment by qusaieilouti99** [comment] 2022-11-27 08:12
This is when we create new PC:
`createConnection: flow(function* (groupId: string, userId: string) {
      const iceServers = yield load("iceServers")
      const connection = new RTCPeerConnection({ iceServers: iceServers })
      const connectionKey = self.getConnectionKey(groupId, userId)
      let makingOffer = false

      connection.addEventListener("negotiationneeded", async () => {
        __DEV__ && console.log("onnegotiationneeded")
        try {
          if (makingOffer || connection.signalingState !== "stable" || connection.localDescription) return
          makingOffer = true
          // adding some state
          self.addConnectionData(connectionKey, { makingOffer: true, glareNumber: new Date().getTime() })
          // create offer
          await connection.setLocalDescription()

          await self.sendCallSdp(groupId, userId, connection.localDescription)
        } finally {
          makingOffer = false
          self.addConnectionData(connectionKey, { makingOffer: false })
        }
      })

      connection.addEventListener("iceconnectionstatechange", (event:any) => {
        switch (event.target.iceConnectionState) {
          case "new":
            __DEV__ && console.log(`WebRtc: ICE candidate new for key=${connectionKey}`)
            break
          case "connected":
            __DEV__ && console.log(`WebRtc: ICE candidate connected for key=${connectionKey}`)
            break
          case "completed":
            __DEV__ && console.log(`WebRtc: ICE candidate completed for key=${connectionKey}`)
            break
          case "checking":
            __DEV__ && console.log(`WebRtc: ICE candidate checking for key=${connectionKey}`)
            break
          case "closed":
            __DEV__ && console.log(`WebRtc: ICE candidate closed for key=${connectionKey}`)
            break
          case "failed": {
            __DEV__ && console.log(`WebRtc: ICE candidate failed for key=${connectionKey}`)
            if (self.hasNetworkIssue) {
              self.reconnectUser(groupId, userId)
            }
            break
          }
          case "disconnected": {
            __DEV__ && console.log(`WebRtc: ICE candidate disconnected for key=${connectionKey}`)
            if (!self.hasNetworkIssue) {
              self.validateConnectionStillActive(groupId, userId)
            }
            break
          }
        }
      })

      connection.addEventListener("connectionstatechange", event => {
        __DEV__ && console.log(`ICE gathering state changed for key=${connectionKey}`)
      })

      connection.addEventListener("signalingstatechange", event => {
        __DEV__ && console.log("signalingstatechange", connection.signalingState)
      })


      connection.addEventListener("icecandidate", (event:RTCIceGathererEvent) => {
        if (event.candidate) {
          self.environment.socket.instance.emit(SocketEvents.SendIceCandidate,
            {
              groupId: groupId,
              userId: userId,
              candidate: event.candidate,
            })
        } else {
          __DEV__ && console.log(`WebRtc: ICE candidate gathering complete for key=${connectionKey}`)
        }
      })

      connection.addEventListener("icecandidateerror", event => {
        __DEV__ && console.log("WebRtc: ICE candidate error", event)
      })

      connection.addEventListener("connectionstatechange", event => {
        switch (connection.connectionState) {
          case "new":
            __DEV__ && console.log(`WebRtc connection: Connecting... for key=${connectionKey}`)
            break
          case "connected":
            __DEV__ && console.log(`WebRtc connection: Online for key=${connectionKey}`)
            self.rootStore.callStore.setIsReconnecting(userId, false)
            break
          case "disconnected":
            __DEV__ && console.log(`WebRtc connection: Disconnecting... for key=${connectionKey}`)
            self.rootStore.callStore.setIsReconnecting(userId, true)
            break
          case "closed":
            __DEV__ && console.log(`WebRtc connection: Offline for key=${connectionKey}`)
            break
          case "failed":
            __DEV__ && console.log(`WebRtc connection: failed for key=${connectionKey}`)
            self.rootStore.callStore.setIsReconnecting(userId, true)
            break
          default:
            __DEV__ && console.log(`WebRtc connection: Unknown key=${connectionKey}`)
            break
        }
      })

      connection.addEventListener("track", (event:RTCTrackEvent) => {
        if(event?.streams.length>0)
        self.rootStore.callStore.addStreamToMember(event.streams[0], userId)
        InCallManager.setForceSpeakerphoneOn(self.rootStore.callStore.call.callType === CallTypeEnum.Video)
      })

      self.connections.set(connectionKey, connection)
    }),`

And this when we receive SDP:
`onReceiveSdp: flow(function* ({ description, groupId, userId, glareNumber }): /* type annotation */ any {
      let polite = false
      let ignoreOffer = false
      try {
        if (description) {
          const connectionKey = self.getConnectionKey(groupId, userId)
          const connection: RTCPeerConnection = self.connections.get(connectionKey)
          if(!connection) return
          const offerCollision = (description.type === "offer") && (self.connectionsData[connectionKey]?.makingOffer || connection.signalingState !== "stable")

          polite = self.connectionsData[connectionKey]?.glareNumber < glareNumber

          ignoreOffer = !polite && offerCollision
          if (ignoreOffer) {
            return
          }

          if (description.type === "offer" && connection.signalingState !== "stable") {
            yield Promise.all([
              connection.setLocalDescription({ type: "rollback" } as any),
              connection.setRemoteDescription(description),
            ])
          } else {
            yield connection.setRemoteDescription(description)
          }

          self.processCandidates(self.getConnectionKey(groupId, userId))
          if (description.type === "offer") {
            yield connection.setLocalDescription()
            yield self.sendCallSdp(groupId, userId, connection.localDescription)
          }
        }
      } catch (err) {
        console.error(err)
      }

    }),`

And this is the code log when the case happened its not logging anything but this:
`2022-11-27 11:08:42.926750+0300 PingMe[3059:160459] [javascript] before rtc creation

2022-11-27 11:08:42.928641+0300 PingMe[3059:160459] [javascript] after rtc creation

2022-11-27 11:08:42.932406+0300 PingMe[3059:160588] [native] Sending `peerConnectionOnRenegotiationNeeded` with no listeners registered.

2022-11-27 11:08:42.941358+0300 PingMe[3059:160459] [javascript] Sending `peerConnectionOnRenegotiationNeeded` with no listeners registered.`

the first 2 logs I added them to make sure its entering the create PC

**Comment by qusaieilouti99** [comment] 2022-11-27 15:15
``
I found that sometimes the onnegotiationneeded is fired before I register them in my PC code 
but as u see I'm registering this right after creating the PC, and as the docs telling, The onnegotiationneeded event will fire after adding the stream to the connection and that's what I'm actually doing 

`The negotiationneeded event is first dispatched to the [RTCPeerConnection](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection) when media is first added to the connection. This starts the process of [ICE](https://developer.mozilla.org/en-US/docs/Glossary/ICE) negotiation by instructing your code to begin exchanging ICE candidates through the signaling server. See [Signaling transaction flow](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling#signaling_transaction_flow) in [Signaling and video calling](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling) for a description of the signaling process that begins with a negotiationneeded event.`

also to make sure it's not a race condition I tried to move this part after registering my events with no results:

` const localStream = self.webrtc.getLocalStream()
        localStream.getTracks().forEach((track) => {
          connection.addTrack(track, localStream)
        })`

**Comment by saghul** [comment] 2022-11-28 09:59
I need to clarify one thing: `peerConnectionOnRenegotiationNeeded` and `onnegotiationneeded` are not the same.

The former is an internal event dispatched by the native side. As I showed above, we register for it immediately when creating the PC. Then, when handle it is when we dispatch the latter.

So the only chance I see for a bogus event to be fired is at PC creation time, which while surprising would be harmless.

You can try to swap lines 80 and 81 here: https://github.com/react-native-webrtc/react-native-webrtc/blob/e903b3133c9c8fd0c56651f889f0f8d08fcc0ba9/src/RTCPeerConnection.ts#L80

Do you get any early onnegotiationneeded events?

**Comment by 8BallBomBom** [comment] 2022-11-28 10:16
> I need to clarify one thing: peerConnectionOnRenegotiationNeeded and onnegotiationneeded are not the same.

My bad on that one but came to the conclusion very unusual and probably harmless 😅

**Comment by qusaieilouti99** [comment] 2022-11-29 10:11
I tried the swap but it still not working as expected 
Can someone please tell me why exactly the  "peerConnectionOnRenegotiationNeeded" event is triggered before even I add any track to the connection ?

**Comment by qusaieilouti99** [comment] 2022-11-29 11:05
In conclusion, I found that its a race condition as you mentioned
well I put the line 80:  `WebRTCModule.peerConnectionInit(configuration, this._pcId);`  inside a setTimeout with a 300 ms 
and now the event is always being triggered and the warning gone.

also I found this on react native docs:  https://reactnative.dev/docs/native-modules-ios#synchronous-methods
**At the moment, we do not recommend using synchronous methods, since calling methods synchronously can have strong performance penalties and introduce threading-related bugs to your native modules. Additionally, please note that if you choose to use RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD, your app can no longer use the Google Chrome debugger. This is because synchronous methods require the JS VM to share memory with the app. For the Google Chrome debugger, React Native runs inside the JS VM in Google Chrome, and communicates asynchronously with the mobile devices via WebSockets.**

The only remaining thing that I couldn't understand is why I receive this event on creation even though I'm adding the track after the creation, is it also a race condition? or its not triggered when adding the track

**Comment by saghul** [comment] 2022-11-29 11:17
> I tried the swap but it still not working as expected

What does this really mean? Is the event fired without listeners or your app is misbehaving?



> Can someone please tell me why exactly the "peerConnectionOnRenegotiationNeeded" event is triggered before even I add any track to the connection ?

Don't you think we'd have told you already if we knew?!



> In conclusion, I found that its a race condition as you mentioned well I put the line 80 for debug purposes: `WebRTCModule.peerConnectionInit(configuration, this._pcId);` inside a setTimeout with a 300 ms and now the event is always being triggered and the warning gone.
> 
> also I found this on react native docs: https://reactnative.dev/docs/native-modules-ios#synchronous-methods **At the moment, we do not recommend using synchronous methods, since calling methods synchronously can have strong performance penalties and introduce threading-related bugs to your native modules. Additionally, please note that if you choose to use RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD, your app can no longer use the Google Chrome debugger. This is because synchronous methods require the JS VM to share memory with the app. For the Google Chrome debugger, React Native runs inside the JS VM in Google Chrome, and communicates asynchronously with the mobile devices via WebSockets.**
> 
> The only remaining thing that I couldn't understand is why I receive this event on creation even though I'm adding the track after the creation, is it also a race condition? or its not triggered when adding the track

I don't understand what's going on :-/

We declare `WebRTCModule.peerConnectionInit` as sync because we need it to be initialized for the next calls to work. By the time that function returns the native PC is created.

Right after we attach a listeners to all native events.

All of this happens in the `RTCPeerConnection` constructor.

So I have no idea how you can end up in that situation.

You are not using the Chrome debugger, are you?

**Comment by qusaieilouti99** [comment] 2022-11-29 12:13
This is the current code that is not working and causing the warning: 
`constructor(configuration) {
    super();
    this._pcId = nextPeerConnectionId++;
    WebRTCModule.peerConnectionInit(configuration, this._pcId);
    this._registerEvents();
    log.debug(`${this._pcId} ctor`);
}`

And this is the fix I added and the flow worked correctly:
`constructor(configuration) {
    super();
    this._pcId = nextPeerConnectionId++;
    this._registerEvents();
    setTimeout(()=>{WebRTCModule.peerConnectionInit(configuration, this._pcId);},300)

    log.debug(`${this._pcId} ctor`);
}`

so does this give you any indicators?

**Comment by 8BallBomBom** [comment] 2022-11-29 14:25
It would seem that something, somehow is managing to squeeze the gap and run before registration of the events is completed.
Which is overly weird and basically has us scratching our heads.

Moving the register function and adding a timeout to the peer connection init shouldn't be needed and isn't exactly ideal.
That potentially could cause more of a race condition.

**Comment by qusaieilouti99** [comment] 2022-11-29 14:53
I know it's not a solution, but I just put it as a debugging step to find the issue.
and since it worked with it then I think we are somewhere close to the real issue

**Comment by saghul** [comment] 2022-11-29 14:56
That still doesn't explain why that event fires so early. But even then, it should be harmless. That also doesn't explain why there is an issue _later_.

**Comment by 8BallBomBom** [comment] 2022-11-29 15:04
Yeah, it is a bit of a pickle.
Might be worth looking into as it doesn't make much sense how it occurs later in the chain.
Definitely a bit of a black hole.
Question is reproduction and debug logging.

**Comment by qusaieilouti99** [comment] 2022-11-29 15:13
I can explain why this causing an issue for me 

I'm creating the offers when I receive the "negotiationneeded" so when I get this warning the "negotiationneeded" isn't triggered again because it has been triggered while PC creation and I didn't have listener yet at that point.

**Comment by qusaieilouti99** [comment] 2022-11-29 15:19
I know again the difference between the "peerConnectionOnRenegotiationNeeded" & "negotiationneeded" 
but when the warning shows up that means the inner listener is not attached so also the outer one will not get an event.
that's why I always talk about "negotiationneeded"

**Comment by 8BallBomBom** [comment] 2022-11-29 15:37
Understandable, if i can manage to reproduce the issue then i'll do some debugging.
But as it stands i'm failing to accomplish the same result after creating and destroying many peer connections.

**Comment by qusaieilouti99** [comment] 2022-11-29 15:40
Thanks for ur efforts guys, btw I'm running this on debug mode on IOS device, the issue isn't showing up in android

**Comment by 8BallBomBom** [comment] 2022-11-29 15:56
That at least narrows it down to being an iOS issue.
Up until now i was testing on Android.

I'll get started on setting up some simulators, hopefully find something.
Can't promise anything though.
It would seem you are the first to report this issue.

**Comment by 8BallBomBom** [comment] 2022-12-07 23:35
Thanks for the report.
So far i haven't had much luck reproducing the issue 😄 
But i'll definitely have a look around some more.

**Comment by 8BallBomBom** [comment] 2022-12-08 06:01
@lkoba Thanks for that, i have managed to reproduce the issue.
Unsure why i wasn't getting anywhere before as i was doing some general basics to get a call started.
One clean project later, the error has rolled in.
Question is where we go from here.

**Comment by saghul** [comment] 2022-12-08 06:28
Since you can repro, what the exact steps?

**Comment by 8BallBomBom** [comment] 2022-12-08 06:48
I'm managing to reproduce the issue within these circumstances.
The first peer connection created each time the app is first loaded will generate the warning.
It all fits into that small time gap of the initial peer creation where you instantly add a track or transceiver.
Seems if i loop to create and destroy then the warning doesn't occur, at least not that i've observed.
Closing the app or totally reloading it will cause the issue and warning as the app state is reset.

Tested with an iPhone 14 simulator and a physical iPhone 13.
Running React-Native 0.70.6 and the latest beta version of the module.
Here is the code i was using.

```javascript
import { mediaDevices, RTCPeerConnection } from 'react-native-webrtc';

let mediaConstraints = {
	audio: true,
	video: true
};

( async () => {
	const mediaStream = await mediaDevices.getUserMedia( mediaConstraints );
	let videoTrack = mediaStream.getVideoTracks()[ 0 ];

	let peerConnection = new RTCPeerConnection();
	peerConnection.addEventListener( 'connectionstatechange', event => {} );
	peerConnection.addEventListener( 'icecandidate', event => {} );
	peerConnection.addEventListener( 'icecandidateerror', event => {} );
	peerConnection.addEventListener( 'iceconnectionstatechange', event => {} );
	peerConnection.addEventListener( 'icegatheringstatechange', event => {} );
	
	peerConnection.addEventListener( 'negotiationneeded', event => {
		console.log( 'negotiation needed' );
	} );
	
	peerConnection.addEventListener( 'signalingstatechange', event => {} );

	let sender_trans = peerConnection.addTransceiver( videoTrack, {
		direction: 'sendonly',
		streams: [ mediaStream ],
		sendEncodings: [
			{
				rid: 'h',
				maxBitrate: 1200 * 1024
			},
			{
				rid: 'm',
				maxBitrate: 600 * 1024,
				scaleResolutionDownBy: 2
			},
			{
				rid: 'l',
				maxBitrate: 300 * 1024,
				scaleResolutionDownBy: 4
			}
		]
	} );
} )();
```

**Comment by saghul** [comment] 2022-12-08 09:01
> The first peer connection created each time the app is first loaded will generate the warning.
> It all fits into that small time gap of the initial peer creation where you instantly add a track or transceiver.

I really can't find a logical explanation for this. There is no difference from the first or third PCs, and the init is synchronous so it shoudl have happend by the time the next call is made 😱

**Comment by 8BallBomBom** [comment] 2022-12-08 09:37
Exactly my thought, it is indeed very unusual.
Been trying to get it to trip and occur by spam creating, adding tracks and then destroying.
No luck as of yet...

Found similar errors on other modules dating back a few years, also iOS.
Weird that it doesn't also happen on Android.
You can prevent the warning just by making the `addListener` function print out the events it adds on execution.
That is how much of a tiny race condition gap there is.

Currently just thinking of a reasonable way to resolve it.

**Comment by saghul** [comment] 2022-12-08 11:14
> You can prevent the warning just by making the `addListener` function print out the events it adds on execution.

What do you mean by this?

> That is how much of a tiny race condition gap there is.

Where do you think the gap is? Because, when the RTCPeerConnection constructor returns the listeners are inplace, and there is no way for the PC constructor to fire any. In fact, if addTrack worked it means it found the PC in the right place. So how on earth can there be no listener attached...

Can you do me a favor and test with RN 0.68.X ?

**Comment by 8BallBomBom** [comment] 2022-12-08 11:36
What i mean by printing on the `addListener` function is literally just telling it to console log all of the events when they're added is enough of a delay to prevent the warning, that is how much of a tiny gap there is.
As for where the gap is, it seems indeed the event registration functions execute before adding tracks/transceivers but the `NativeEventEmitter` lags behind by a little so the event gets triggered just before registration.

I can most certainly test, will get on that now 👍🏻

**Comment by saghul** [comment] 2022-12-08 12:24
Can either of you try to bisect what beta introduced this? I'll try to find some time for it hopefully tomorrow.

**Comment by 8BallBomBom** [comment] 2022-12-08 12:53
I will go over a few versions running up to the latest and see if i can pin point when the issue started 👍🏻 
Have a feeling it might have been there a long while but kept hidden 😨

**Comment by qusaieilouti99** [comment] 2022-12-08 13:00
> I will go over a few versions running up to the latest and see if i can pin point when the issue started 👍🏻 Have a feeling it might have been there a long while but kept hidden 😨

There is a huge possibility for that, for example, I wasn't using perfect negotiation before, I was just sending an offer from one peer and the other peer should send an answer, so there was no need for "negotiationneeded" event to start signaling

**Comment by saghul** [comment] 2022-12-08 13:19
Can either of you please try this patch? https://github.com/react-native-webrtc/react-native-webrtc/pull/1246

I have a theory...

Calling `addListener` will result in calling RCTEventEmitter's method: https://github.com/facebook/react-native/blob/b12a7f9e68891a2423df2494b306b081a192a967/React/Modules/RCTEventEmitter.m#L100 which, being a RN method is async.

When calling `addTrack` synchronously we will block the JS thread. Thus, at that stage al we are running is addTrack. addTrack will fire an event on the stpot, and, as you can see from the PR, we are emitting it to JS right there.

So I *think* by the time we come back to the JS thread it's possible the native listener was not added because our sync method blocks the JS thread.

In the PR I deferred the delegate event to the dedicated WebRTC thread we use for operations. This needs to be done for all events in the end, but I only did it for the one raised here so we can validate the approach.

**Comment by 8BallBomBom** [comment] 2022-12-08 13:20
Alrighty, i'm on it 👍🏻

**Comment by 8BallBomBom** [comment] 2022-12-08 13:37
Just did a rebuild, didn't seem to make any difference, gonna try fresh and test again 😨

**Comment by qusaieilouti99** [comment] 2022-12-08 14:11
might this issue be related ? because it talks about an event not being triggered but in android. 
 [issue](https://github.com/react-native-webrtc/react-native-webrtc/issues/1241)

**Comment by 8BallBomBom** [comment] 2022-12-08 14:20
At this point it is hard to tell but it could indeed be related.
They might be experiencing the same issue which then also means other events don't get triggered.

**Comment by saghul** [comment] 2022-12-08 15:47
I have another idea we can try, I'll try to give it a shot tomorrow. The basic idea would be to add listeners for all the native events on the native side at import time and then each PC will just latch on to those.

**Comment by 8BallBomBom** [comment] 2022-12-08 16:02
Sounds good to me, ready to test on both platforms when needed 😃

**Comment by saghul** [comment] 2022-12-09 14:29
I implemented that in https://github.com/react-native-webrtc/react-native-webrtc/pull/1246 (untested). If someone can give it a go I'd appreciate that!

**Comment by 8BallBomBom** [comment] 2022-12-11 10:44
@qusaieilouti99 @lkoba Thanks for the report and help narrowing down the issue.
Had us bashing our heads for a while.

This issue should be resolved with the next beta release going out soon.
@saghul Great work as always 👍🏻

**Comment by saghul** [comment] 2022-12-12 10:55
Beta 8 is out, can you give it another try?

**Closed** 2022-12-13 09:01 UTC
